// Verbformen database
// Modal verbs: the stored participle is the standalone/Vollverb Partizip II.
// With another infinitive, German commonly uses the Ersatzinfinitiv
// (e.g. "Ich habe arbeiten müssen").
const VERBS = [
  { infinitive: "anfangen", translation: "начинать", preterite: "fing an", participle: "angefangen", auxiliary: "haben", example: "Wir haben um neun Uhr angefangen.", priority: 2 },
  { infinitive: "ankommen", translation: "прибывать", preterite: "kam an", participle: "angekommen", auxiliary: "sein", example: "Der Zug ist pünktlich angekommen.", priority: 2 },
  { infinitive: "aufstehen", translation: "вставать", preterite: "stand auf", participle: "aufgestanden", auxiliary: "sein", example: "Ich bin heute früh aufgestanden.", priority: 2 },
  { infinitive: "beginnen", translation: "начинать", preterite: "begann", participle: "begonnen", auxiliary: "haben", example: "Der Kurs hat im September begonnen.", priority: 2 },
  { infinitive: "bekommen", translation: "получать", preterite: "bekam", participle: "bekommen", auxiliary: "haben", example: "Ich habe eine Nachricht bekommen.", priority: 1 },
  { infinitive: "bleiben", translation: "оставаться", preterite: "blieb", participle: "geblieben", auxiliary: "sein", example: "Ich bin zu Hause geblieben.", priority: 2 },
  { infinitive: "bringen", translation: "приносить; привозить", preterite: "brachte", participle: "gebracht", auxiliary: "haben", example: "Sie hat die Unterlagen mitgebracht.", priority: 2 },
  { infinitive: "denken", translation: "думать", preterite: "dachte", participle: "gedacht", auxiliary: "haben", example: "Ich habe oft daran gedacht.", priority: 2 },
  { infinitive: "dürfen", translation: "мочь; иметь разрешение", preterite: "durfte", participle: "gedurft", auxiliary: "haben", example: "Als Vollverb: Das habe ich nicht gedurft.", priority: 2, modal: true },
  { infinitive: "empfehlen", translation: "рекомендовать", preterite: "empfahl", participle: "empfohlen", auxiliary: "haben", example: "Der Arzt hat mir das empfohlen.", priority: 1 },
  { infinitive: "entscheiden", translation: "решать", preterite: "entschied", participle: "entschieden", auxiliary: "haben", example: "Ich habe mich anders entschieden.", priority: 1 },
  { infinitive: "essen", translation: "есть", preterite: "aß", participle: "gegessen", auxiliary: "haben", example: "Wir haben zusammen gegessen.", priority: 2 },
  { infinitive: "fahren", translation: "ехать; водить", preterite: "fuhr", participle: "gefahren", auxiliary: "sein / haben", example: "Ich bin mit dem Zug gefahren.", priority: 2 },
  { infinitive: "fallen", translation: "падать", preterite: "fiel", participle: "gefallen", auxiliary: "sein", example: "Das Glas ist auf den Boden gefallen.", priority: 2 },
  { infinitive: "fangen", translation: "ловить", preterite: "fing", participle: "gefangen", auxiliary: "haben", example: "Er hat den Ball gefangen.", priority: 2 },
  { infinitive: "finden", translation: "находить", preterite: "fand", participle: "gefunden", auxiliary: "haben", example: "Ich habe meinen Schlüssel gefunden.", priority: 1 },
  { infinitive: "fliegen", translation: "лететь; летать", preterite: "flog", participle: "geflogen", auxiliary: "sein / haben", example: "Wir sind nach Berlin geflogen.", priority: 2 },
  { infinitive: "geben", translation: "давать", preterite: "gab", participle: "gegeben", auxiliary: "haben", example: "Sie hat mir einen Tipp gegeben.", priority: 1 },
  { infinitive: "gehen", translation: "идти", preterite: "ging", participle: "gegangen", auxiliary: "sein", example: "Ich bin nach Hause gegangen.", priority: 1 },
  { infinitive: "gewinnen", translation: "выигрывать", preterite: "gewann", participle: "gewonnen", auxiliary: "haben", example: "Unsere Mannschaft hat gewonnen.", priority: 2 },
  { infinitive: "haben", translation: "иметь", preterite: "hatte", participle: "gehabt", auxiliary: "haben", example: "Ich habe keine Zeit gehabt.", priority: 1 },
  { infinitive: "halten", translation: "держать; останавливаться", preterite: "hielt", participle: "gehalten", auxiliary: "haben", example: "Der Bus hat an der Haltestelle gehalten.", priority: 1 },
  { infinitive: "heißen", translation: "называться; означать", preterite: "hieß", participle: "geheißen", auxiliary: "haben", example: "Wie hat das Restaurant geheißen?", priority: 1 },
  { infinitive: "helfen", translation: "помогать", preterite: "half", participle: "geholfen", auxiliary: "haben", example: "Meine Freundin hat mir geholfen.", priority: 2 },
  { infinitive: "kennen", translation: "знать; быть знакомым", preterite: "kannte", participle: "gekannt", auxiliary: "haben", example: "Ich habe ihn schon lange gekannt.", priority: 1 },
  { infinitive: "kommen", translation: "приходить; приезжать", preterite: "kam", participle: "gekommen", auxiliary: "sein", example: "Sie ist zu spät gekommen.", priority: 2 },
  { infinitive: "lassen", translation: "оставлять; позволять", preterite: "ließ", participle: "gelassen", auxiliary: "haben", example: "Ich habe mein Handy zu Hause gelassen.", priority: 1 },
  { infinitive: "laufen", translation: "бежать; ходить", preterite: "lief", participle: "gelaufen", auxiliary: "sein", example: "Wir sind durch den Park gelaufen.", priority: 1 },
  { infinitive: "lesen", translation: "читать", preterite: "las", participle: "gelesen", auxiliary: "haben", example: "Ich habe den Artikel gelesen.", priority: 1 },
  { infinitive: "liegen", translation: "лежать; находиться", preterite: "lag", participle: "gelegen", auxiliary: "haben", example: "Das Buch hat auf dem Tisch gelegen.", priority: 1 },
  { infinitive: "nehmen", translation: "брать", preterite: "nahm", participle: "genommen", auxiliary: "haben", example: "Ich habe den Bus genommen.", priority: 1 },
  { infinitive: "nennen", translation: "называть", preterite: "nannte", participle: "genannt", auxiliary: "haben", example: "Er hat keinen Namen genannt.", priority: 1 },
  { infinitive: "rufen", translation: "звать; звонить", preterite: "rief", participle: "gerufen", auxiliary: "haben", example: "Sie hat nach mir gerufen.", priority: 1 },
  { infinitive: "schlafen", translation: "спать", preterite: "schlief", participle: "geschlafen", auxiliary: "haben", example: "Ich habe schlecht geschlafen.", priority: 2 },
  { infinitive: "schließen", translation: "закрывать", preterite: "schloss", participle: "geschlossen", auxiliary: "haben", example: "Ich habe die Tür geschlossen.", priority: 1 },
  { infinitive: "schneiden", translation: "резать", preterite: "schnitt", participle: "geschnitten", auxiliary: "haben", example: "Ich habe das Gemüse geschnitten.", priority: 2 },
  { infinitive: "schreiben", translation: "писать", preterite: "schrieb", participle: "geschrieben", auxiliary: "haben", example: "Ich habe eine E-Mail geschrieben.", priority: 1 },
  { infinitive: "schwimmen", translation: "плавать", preterite: "schwamm", participle: "geschwommen", auxiliary: "sein / haben", example: "Wir sind im See geschwommen.", priority: 2 },
  { infinitive: "sehen", translation: "видеть", preterite: "sah", participle: "gesehen", auxiliary: "haben", example: "Ich habe den Film schon gesehen.", priority: 1 },
  { infinitive: "sein", translation: "быть", preterite: "war", participle: "gewesen", auxiliary: "sein", example: "Ich bin noch nie dort gewesen.", priority: 2 },
  { infinitive: "singen", translation: "петь", preterite: "sang", participle: "gesungen", auxiliary: "haben", example: "Wir haben zusammen gesungen.", priority: 2 },
  { infinitive: "sitzen", translation: "сидеть", preterite: "saß", participle: "gesessen", auxiliary: "haben", example: "Wir haben draußen gesessen.", priority: 2 },
  { infinitive: "sprechen", translation: "говорить", preterite: "sprach", participle: "gesprochen", auxiliary: "haben", example: "Ich habe mit meiner Chefin gesprochen.", priority: 2 },
  { infinitive: "stehen", translation: "стоять", preterite: "stand", participle: "gestanden", auxiliary: "haben", example: "Das Auto hat vor dem Haus gestanden.", priority: 2 },
  { infinitive: "steigen", translation: "подниматься", preterite: "stieg", participle: "gestiegen", auxiliary: "sein", example: "Die Preise sind gestiegen.", priority: 1 },
  { infinitive: "sterben", translation: "умирать", preterite: "starb", participle: "gestorben", auxiliary: "sein", example: "Der Schauspieler ist 2020 gestorben.", priority: 1 },
  { infinitive: "tragen", translation: "носить; нести", preterite: "trug", participle: "getragen", auxiliary: "haben", example: "Sie hat ein schwarzes Kleid getragen.", priority: 1 },
  { infinitive: "treffen", translation: "встречать", preterite: "traf", participle: "getroffen", auxiliary: "haben", example: "Ich habe gestern Freunde getroffen.", priority: 1 },
  { infinitive: "trinken", translation: "пить", preterite: "trank", participle: "getrunken", auxiliary: "haben", example: "Ich habe genug Wasser getrunken.", priority: 1 },
  { infinitive: "tun", translation: "делать", preterite: "tat", participle: "getan", auxiliary: "haben", example: "Ich habe alles getan, was ich konnte.", priority: 1 },
  { infinitive: "vergessen", translation: "забывать", preterite: "vergaß", participle: "vergessen", auxiliary: "haben", example: "Ich habe den Termin vergessen.", priority: 2 },
  { infinitive: "verlieren", translation: "терять; проигрывать", preterite: "verlor", participle: "verloren", auxiliary: "haben", example: "Ich habe meine Karte verloren.", priority: 1 },
  { infinitive: "verstehen", translation: "понимать", preterite: "verstand", participle: "verstanden", auxiliary: "haben", example: "Ich habe die Frage verstanden.", priority: 2 },
  { infinitive: "werden", translation: "становиться", preterite: "wurde", participle: "geworden", auxiliary: "sein", example: "Es ist spät geworden.", priority: 2 },
  { infinitive: "werfen", translation: "бросать", preterite: "warf", participle: "geworfen", auxiliary: "haben", example: "Er hat den Ball geworfen.", priority: 1 },
  { infinitive: "wissen", translation: "знать", preterite: "wusste", participle: "gewusst", auxiliary: "haben", example: "Das habe ich nicht gewusst.", priority: 1 },
  { infinitive: "ziehen", translation: "тянуть; переезжать", preterite: "zog", participle: "gezogen", auxiliary: "sein / haben", example: "Sie ist nach München gezogen.", priority: 1 },
  { infinitive: "bieten", translation: "предлагать", preterite: "bot", participle: "geboten", auxiliary: "haben", example: "Die Firma hat mir eine Stelle geboten.", priority: 1 },
  { infinitive: "bitten", translation: "просить", preterite: "bat", participle: "gebeten", auxiliary: "haben", example: "Ich habe ihn um Hilfe gebeten.", priority: 1 },
  { infinitive: "brechen", translation: "ломать(ся)", preterite: "brach", participle: "gebrochen", auxiliary: "haben / sein", example: "Ich habe mir den Arm gebrochen.", priority: 1 },
  { infinitive: "brennen", translation: "гореть", preterite: "brannte", participle: "gebrannt", auxiliary: "haben", example: "Das Licht hat die ganze Nacht gebrannt.", priority: 1 },
  { infinitive: "einladen", translation: "приглашать", preterite: "lud ein", participle: "eingeladen", auxiliary: "haben", example: "Sie hat mich zum Essen eingeladen.", priority: 1 },
  { infinitive: "einschlafen", translation: "засыпать", preterite: "schlief ein", participle: "eingeschlafen", auxiliary: "sein", example: "Ich bin sofort eingeschlafen.", priority: 1 },
  { infinitive: "erfahren", translation: "узнавать", preterite: "erfuhr", participle: "erfahren", auxiliary: "haben", example: "Ich habe es erst gestern erfahren.", priority: 1 },
  { infinitive: "erhalten", translation: "получать", preterite: "erhielt", participle: "erhalten", auxiliary: "haben", example: "Ich habe eine Antwort erhalten.", priority: 1 },
  { infinitive: "erkennen", translation: "узнавать; распознавать", preterite: "erkannte", participle: "erkannt", auxiliary: "haben", example: "Ich habe ihn sofort erkannt.", priority: 1 },
  { infinitive: "erscheinen", translation: "появляться; выходить", preterite: "erschien", participle: "erschienen", auxiliary: "sein", example: "Der Artikel ist gestern erschienen.", priority: 1 },
  { infinitive: "geschehen", translation: "происходить", preterite: "geschah", participle: "geschehen", auxiliary: "sein", example: "Was ist hier geschehen?", priority: 1 },
  { infinitive: "leihen", translation: "одалживать", preterite: "lieh", participle: "geliehen", auxiliary: "haben", example: "Ich habe mir ein Fahrrad geliehen.", priority: 1 },
  { infinitive: "lügen", translation: "лгать", preterite: "log", participle: "gelogen", auxiliary: "haben", example: "Er hat mich angelogen.", priority: 1 },
  { infinitive: "riechen", translation: "пахнуть; нюхать", preterite: "roch", participle: "gerochen", auxiliary: "haben", example: "Das Essen hat gut gerochen.", priority: 1 },
  { infinitive: "scheinen", translation: "светить; казаться", preterite: "schien", participle: "geschienen", auxiliary: "haben", example: "Die Sonne hat den ganzen Tag geschienen.", priority: 1 },
  { infinitive: "schieben", translation: "толкать; двигать", preterite: "schob", participle: "geschoben", auxiliary: "haben", example: "Ich habe den Tisch zur Seite geschoben.", priority: 1 },
  { infinitive: "springen", translation: "прыгать", preterite: "sprang", participle: "gesprungen", auxiliary: "sein", example: "Das Kind ist ins Wasser gesprungen.", priority: 1 },
  { infinitive: "streiten", translation: "ссориться; спорить", preterite: "stritt", participle: "gestritten", auxiliary: "haben", example: "Wir haben uns darüber gestritten.", priority: 1 },
  { infinitive: "teilnehmen", translation: "участвовать", preterite: "nahm teil", participle: "teilgenommen", auxiliary: "haben", example: "Ich habe an dem Kurs teilgenommen.", priority: 1 },
  { infinitive: "verbinden", translation: "соединять; связывать", preterite: "verband", participle: "verbunden", auxiliary: "haben", example: "Ich habe das Handy mit dem WLAN verbunden.", priority: 1 },
  { infinitive: "versprechen", translation: "обещать", preterite: "versprach", participle: "versprochen", auxiliary: "haben", example: "Ich habe es dir versprochen.", priority: 1 },
  { infinitive: "waschen", translation: "мыть; стирать", preterite: "wusch", participle: "gewaschen", auxiliary: "haben", example: "Ich habe mir die Hände gewaschen.", priority: 1 },
  { infinitive: "wachsen", translation: "расти", preterite: "wuchs", participle: "gewachsen", auxiliary: "sein", example: "Die Stadt ist schnell gewachsen.", priority: 1 },
  { infinitive: "können", translation: "мочь; уметь", preterite: "konnte", participle: "gekonnt", auxiliary: "haben", example: "Als Vollverb: Das habe ich früher besser gekonnt.", priority: 2, modal: true },
  { infinitive: "mögen", translation: "любить; нравиться", preterite: "mochte", participle: "gemocht", auxiliary: "haben", example: "Ich habe diesen Film sehr gemocht.", priority: 2, modal: true },
  { infinitive: "müssen", translation: "быть должным; быть вынужденным", preterite: "musste", participle: "gemusst", auxiliary: "haben", example: "Als Vollverb: Ich habe heute nicht gemusst.", priority: 2, modal: true },
  { infinitive: "sollen", translation: "быть должным; следовать указанию", preterite: "sollte", participle: "gesollt", auxiliary: "haben", example: "Als Vollverb: Das habe ich nicht gesollt.", priority: 2, modal: true },
  { infinitive: "wollen", translation: "хотеть", preterite: "wollte", participle: "gewollt", auxiliary: "haben", example: "Das habe ich nicht gewollt.", priority: 2, modal: true },
];
