// Verbformen database
// Modal verbs: the stored participle is the standalone/Vollverb Partizip II.
// With another infinitive, German commonly uses the Ersatzinfinitiv
// (e.g. "Ich habe arbeiten müssen").
const VERBS = [
  { infinitive: "anfangen", pattern: "a - i - a", translation: "начинать", preterite: "fing an", participle: "angefangen", auxiliary: "haben", example: "Wir haben um neun Uhr angefangen.", priority: 2 },
  { infinitive: "beginnen", pattern: "i - a - o", translation: "начинать", preterite: "begann", participle: "begonnen", auxiliary: "haben", example: "Der Kurs hat im September begonnen.", priority: 2 },
  { infinitive: "bekommen", pattern: "o - a - o", translation: "получать", preterite: "bekam", participle: "bekommen", auxiliary: "haben", example: "Ich habe eine Nachricht bekommen.", priority: 1 },
  { infinitive: "bleiben", pattern: "ei - ie - ie", translation: "оставаться", preterite: "blieb", participle: "geblieben", auxiliary: "sein", example: "Ich bin zu Hause geblieben.", priority: 2 },
  { infinitive: "bringen", pattern: "i - a - a", translation: "приносить; привозить", preterite: "brachte", participle: "gebracht", auxiliary: "haben", example: "Sie hat mir einen Kaffee gebracht.", priority: 2 },
  { infinitive: "denken", pattern: "e - a - a", translation: "думать", preterite: "dachte", participle: "gedacht", auxiliary: "haben", example: "Ich habe oft daran gedacht.", priority: 2 },
  { infinitive: "dürfen", pattern: "ü - u - u", translation: "мочь; иметь разрешение", preterite: "durfte", participle: "gedurft", auxiliary: "haben", example: "Als Vollverb: Das habe ich nicht gedurft.", priority: 2, modal: true },
  { infinitive: "empfehlen", pattern: "e - a - o", translation: "рекомендовать", preterite: "empfahl", participle: "empfohlen", auxiliary: "haben", example: "Der Arzt hat mir das empfohlen.", priority: 1 },
  { infinitive: "entscheiden", pattern: "ei - ie - ie", translation: "решать", preterite: "entschied", participle: "entschieden", auxiliary: "haben", example: "Ich habe mich anders entschieden.", priority: 1 },
  { infinitive: "essen", pattern: "e - a - e", translation: "есть", preterite: "aß", participle: "gegessen", auxiliary: "haben", example: "Wir haben zusammen gegessen.", priority: 2 },
  { infinitive: "fahren", pattern: "a - u - a", translation: "ехать; водить", preterite: "fuhr", participle: "gefahren", auxiliary: "sein / haben", example: "Ich bin mit dem Zug gefahren.", priority: 2 },
  { infinitive: "fallen", pattern: "a - ie - a", translation: "падать", preterite: "fiel", participle: "gefallen", auxiliary: "sein", example: "Das Glas ist auf den Boden gefallen.", priority: 2 },
  { infinitive: "finden", pattern: "i - a - u", translation: "находить", preterite: "fand", participle: "gefunden", auxiliary: "haben", example: "Ich habe meinen Schlüssel gefunden.", priority: 1 },
  { infinitive: "fliegen", pattern: "ie - o - o", translation: "лететь; летать", preterite: "flog", participle: "geflogen", auxiliary: "sein / haben", example: "Wir sind nach Berlin geflogen.", priority: 2 },
  { infinitive: "geben", pattern: "e - a - e", translation: "давать", preterite: "gab", participle: "gegeben", auxiliary: "haben", example: "Sie hat mir einen Tipp gegeben.", priority: 1 },
  { infinitive: "gehen", pattern: "e - i - a", translation: "идти", preterite: "ging", participle: "gegangen", auxiliary: "sein", example: "Ich bin nach Hause gegangen.", priority: 1 },
  { infinitive: "gewinnen", pattern: "i - a - o", translation: "выигрывать", preterite: "gewann", participle: "gewonnen", auxiliary: "haben", example: "Unsere Mannschaft hat gewonnen.", priority: 2 },
  { infinitive: "haben", pattern: "a - a - a", translation: "иметь", preterite: "hatte", participle: "gehabt", auxiliary: "haben", example: "Ich habe keine Zeit gehabt.", priority: 1 },
  { infinitive: "halten", pattern: "a - ie - a", translation: "держать; останавливаться", preterite: "hielt", participle: "gehalten", auxiliary: "haben", example: "Der Bus hat an der Haltestelle gehalten.", priority: 1 },
  { infinitive: "heißen", pattern: "ei - ie - ei", translation: "называться; означать", preterite: "hieß", participle: "geheißen", auxiliary: "haben", example: "Wie hat das Restaurant geheißen?", priority: 1 },
  { infinitive: "helfen", pattern: "e - a - o", translation: "помогать", preterite: "half", participle: "geholfen", auxiliary: "haben", example: "Meine Freundin hat mir geholfen.", priority: 2 },
  { infinitive: "kennen", pattern: "e - a - a", translation: "знать; быть знакомым", preterite: "kannte", participle: "gekannt", auxiliary: "haben", example: "Ich habe ihn gar nicht gekannt.", priority: 1 },
  { infinitive: "kommen", pattern: "o - a - o", translation: "приходить; приезжать", preterite: "kam", participle: "gekommen", auxiliary: "sein", example: "Sie ist zu spät gekommen.", priority: 2 },
  { infinitive: "lassen", pattern: "a - ie - a", translation: "оставлять; позволять", preterite: "ließ", participle: "gelassen", auxiliary: "haben", example: "Ich habe mein Handy zu Hause gelassen.", priority: 1 },
  { infinitive: "laufen", pattern: "au - ie - au", translation: "бежать; ходить", preterite: "lief", participle: "gelaufen", auxiliary: "sein", example: "Wir sind durch den Park gelaufen.", priority: 1 },
  { infinitive: "lesen", pattern: "e - a - e", translation: "читать", preterite: "las", participle: "gelesen", auxiliary: "haben", example: "Ich habe den Artikel gelesen.", priority: 1 },
  { infinitive: "liegen", pattern: "ie - a - e", translation: "лежать; находиться", preterite: "lag", participle: "gelegen", auxiliary: "haben", example: "Das Buch hat auf dem Tisch gelegen.", priority: 1 },
  { infinitive: "nehmen", pattern: "e - a - o", translation: "брать", preterite: "nahm", participle: "genommen", auxiliary: "haben", example: "Ich habe den Bus genommen.", priority: 1 },
  { infinitive: "nennen", pattern: "e - a - a", translation: "называть", preterite: "nannte", participle: "genannt", auxiliary: "haben", example: "Er hat keinen Namen genannt.", priority: 1 },
  { infinitive: "rufen", pattern: "u - ie - u", translation: "звать; вызывать (врача, такси)", preterite: "rief", participle: "gerufen", auxiliary: "haben", example: "Sie hat nach mir gerufen.", priority: 1 },
  { infinitive: "schlafen", pattern: "a - ie - a", translation: "спать", preterite: "schlief", participle: "geschlafen", auxiliary: "haben", example: "Ich habe schlecht geschlafen.", priority: 2 },
  { infinitive: "schließen", pattern: "ie - o - o", translation: "закрывать", preterite: "schloss", participle: "geschlossen", auxiliary: "haben", example: "Ich habe die Tür geschlossen.", priority: 1 },
  { infinitive: "schneiden", pattern: "ei - i - i", translation: "резать", preterite: "schnitt", participle: "geschnitten", auxiliary: "haben", example: "Ich habe das Gemüse geschnitten.", priority: 2 },
  { infinitive: "schreiben", pattern: "ei - ie - ie", translation: "писать", preterite: "schrieb", participle: "geschrieben", auxiliary: "haben", example: "Ich habe eine E-Mail geschrieben.", priority: 1 },
  { infinitive: "schwimmen", pattern: "i - a - o", translation: "плавать", preterite: "schwamm", participle: "geschwommen", auxiliary: "sein / haben", example: "Wir sind im See geschwommen.", priority: 2 },
  { infinitive: "sehen", pattern: "e - a - e", translation: "видеть", preterite: "sah", participle: "gesehen", auxiliary: "haben", example: "Ich habe den Film schon gesehen.", priority: 1 },
  { infinitive: "sein", pattern: "ei - a - e", translation: "быть", preterite: "war", participle: "gewesen", auxiliary: "sein", example: "Ich bin noch nie dort gewesen.", priority: 2 },
  { infinitive: "singen", pattern: "i - a - u", translation: "петь", preterite: "sang", participle: "gesungen", auxiliary: "haben", example: "Wir haben zusammen gesungen.", priority: 2 },
  { infinitive: "sitzen", pattern: "i - a - e", translation: "сидеть", preterite: "saß", participle: "gesessen", auxiliary: "haben", example: "Wir haben draußen gesessen.", priority: 2 },
  { infinitive: "sprechen", pattern: "e - a - o", translation: "говорить", preterite: "sprach", participle: "gesprochen", auxiliary: "haben", example: "Ich habe mit meiner Chefin gesprochen.", priority: 2 },
  { infinitive: "stehen", pattern: "e - a - a", translation: "стоять", preterite: "stand", participle: "gestanden", auxiliary: "haben", example: "Das Auto hat vor dem Haus gestanden.", priority: 2 },
  { infinitive: "steigen", pattern: "ei - ie - ie", translation: "подниматься; расти (о ценах)", preterite: "stieg", participle: "gestiegen", auxiliary: "sein", example: "Die Preise sind gestiegen.", priority: 1 },
  { infinitive: "sterben", pattern: "e - a - o", translation: "умирать", preterite: "starb", participle: "gestorben", auxiliary: "sein", example: "Der Schauspieler ist 2020 gestorben.", priority: 1 },
  { infinitive: "tragen", pattern: "a - u - a", translation: "носить; нести", preterite: "trug", participle: "getragen", auxiliary: "haben", example: "Sie hat ein schwarzes Kleid getragen.", priority: 1 },
  { infinitive: "treffen", pattern: "e - a - o", translation: "встречать", preterite: "traf", participle: "getroffen", auxiliary: "haben", example: "Ich habe gestern Freunde getroffen.", priority: 1 },
  { infinitive: "trinken", pattern: "i - a - u", translation: "пить", preterite: "trank", participle: "getrunken", auxiliary: "haben", example: "Ich habe genug Wasser getrunken.", priority: 1 },
  { infinitive: "tun", pattern: "u - a - a", translation: "делать", preterite: "tat", participle: "getan", auxiliary: "haben", example: "Ich habe alles getan, was ich konnte.", priority: 1 },
  { infinitive: "vergessen", pattern: "e - a - e", translation: "забывать", preterite: "vergaß", participle: "vergessen", auxiliary: "haben", example: "Ich habe den Termin vergessen.", priority: 2 },
  { infinitive: "verlieren", pattern: "ie - o - o", translation: "терять; проигрывать", preterite: "verlor", participle: "verloren", auxiliary: "haben", example: "Ich habe meine Karte verloren.", priority: 1 },
  { infinitive: "verstehen", pattern: "e - a - a", translation: "понимать", preterite: "verstand", participle: "verstanden", auxiliary: "haben", example: "Ich habe die Frage verstanden.", priority: 2 },
  { infinitive: "werden", pattern: "e - u - o", translation: "становиться", preterite: "wurde", participle: "geworden", auxiliary: "sein", example: "Es ist spät geworden.", priority: 2 },
  { infinitive: "werfen", pattern: "e - a - o", translation: "бросать", preterite: "warf", participle: "geworfen", auxiliary: "haben", example: "Er hat den Ball geworfen.", priority: 1 },
  { infinitive: "wissen", pattern: "i - u - u", translation: "знать", preterite: "wusste", participle: "gewusst", auxiliary: "haben", example: "Das habe ich nicht gewusst.", priority: 1 },
  { infinitive: "ziehen", pattern: "ie - o - o", translation: "тянуть; переезжать", preterite: "zog", participle: "gezogen", auxiliary: "sein / haben", example: "Sie ist nach München gezogen.", priority: 1 },
  { infinitive: "anbieten", pattern: "ie - o - o", translation: "предлагать", preterite: "bot an", participle: "angeboten", auxiliary: "haben", example: "Sie hat mir einen Job angeboten.", priority: 1 },
  { infinitive: "bitten", pattern: "i - a - e", translation: "просить", preterite: "bat", participle: "gebeten", auxiliary: "haben", example: "Ich habe ihn um Hilfe gebeten.", priority: 1 },
  { infinitive: "brechen", pattern: "e - a - o", translation: "ломать(ся)", preterite: "brach", participle: "gebrochen", auxiliary: "haben / sein", example: "Ich habe mir den Arm gebrochen.", priority: 1 },
  { infinitive: "einladen", pattern: "a - u - a", translation: "приглашать", preterite: "lud ein", participle: "eingeladen", auxiliary: "haben", example: "Sie hat mich zum Essen eingeladen.", priority: 1 },
  { infinitive: "geschehen", pattern: "e - a - e", translation: "происходить", preterite: "geschah", participle: "geschehen", auxiliary: "sein", example: "Was ist hier geschehen?", priority: 1 },
  { infinitive: "leihen", pattern: "ei - ie - ie", translation: "одалживать", preterite: "lieh", participle: "geliehen", auxiliary: "haben", example: "Ich habe mir ein Fahrrad geliehen.", priority: 1 },
  { infinitive: "lügen", pattern: "ü - o - o", translation: "лгать", preterite: "log", participle: "gelogen", auxiliary: "haben", example: "Das Kind hat nicht gelogen.", priority: 1 },
  { infinitive: "riechen", pattern: "ie - o - o", translation: "пахнуть; нюхать", preterite: "roch", participle: "gerochen", auxiliary: "haben", example: "Das Essen hat gut gerochen.", priority: 1 },
  { infinitive: "scheinen", pattern: "ei - ie - ie", translation: "светить; казаться", preterite: "schien", participle: "geschienen", auxiliary: "haben", example: "Die Sonne hat den ganzen Tag geschienen.", priority: 1 },
  { infinitive: "springen", pattern: "i - a - u", translation: "прыгать", preterite: "sprang", participle: "gesprungen", auxiliary: "sein", example: "Das Kind ist ins Wasser gesprungen.", priority: 1 },
  { infinitive: "streiten", pattern: "ei - i - i", translation: "ссориться; спорить", preterite: "stritt", participle: "gestritten", auxiliary: "haben", example: "Wir haben uns darüber gestritten.", priority: 1 },
  { infinitive: "verbinden", pattern: "i - a - u", translation: "соединять; связывать", preterite: "verband", participle: "verbunden", auxiliary: "haben", example: "Ich habe das Handy mit dem WLAN verbunden.", priority: 1 },
  { infinitive: "waschen", pattern: "a - u - a", translation: "мыть; стирать", preterite: "wusch", participle: "gewaschen", auxiliary: "haben", example: "Ich habe mir die Hände gewaschen.", priority: 1 },
  { infinitive: "wachsen", pattern: "a - u - a", translation: "расти", preterite: "wuchs", participle: "gewachsen", auxiliary: "sein", example: "Die Stadt ist schnell gewachsen.", priority: 1 },
  { infinitive: "genießen", pattern: "ie - o - o", translation: "наслаждаться", preterite: "genoss", participle: "genossen", auxiliary: "haben", example: "Wir haben den Urlaub sehr genossen.", priority: 1 },
  { infinitive: "vergleichen", pattern: "ei - i - i", translation: "сравнивать", preterite: "verglich", participle: "verglichen", auxiliary: "haben", example: "Ich habe die Preise verglichen.", priority: 1 },
  { infinitive: "gelingen", pattern: "i - a - u", translation: "удаваться", preterite: "gelang", participle: "gelungen", auxiliary: "sein", example: "Der Kuchen ist mir gut gelungen.", priority: 1 },
  { infinitive: "verschwinden", pattern: "i - a - u", translation: "исчезать", preterite: "verschwand", participle: "verschwunden", auxiliary: "sein", example: "Mein Schlüssel ist verschwunden.", priority: 1 },
  { infinitive: "stehlen", pattern: "e - a - o", translation: "красть", preterite: "stahl", participle: "gestohlen", auxiliary: "haben", example: "Jemand hat mein Fahrrad gestohlen.", priority: 1 },
  { infinitive: "backen", pattern: "a - a - a", translation: "печь", preterite: "backte", participle: "gebacken", auxiliary: "haben", example: "Ich habe einen Kuchen gebacken.", priority: 1 },
  { infinitive: "hängen", pattern: "ä - i - a", translation: "висеть", preterite: "hing", participle: "gehangen", auxiliary: "haben", example: "Das Bild hat lange an der Wand gehangen.", priority: 1 },
  { infinitive: "raten", pattern: "a - ie - a", translation: "советовать; угадывать", preterite: "riet", participle: "geraten", auxiliary: "haben", example: "Der Arzt hat mir zu mehr Sport geraten.", priority: 1 },
  { infinitive: "rennen", pattern: "e - a - a", translation: "мчаться; бежать бегом", preterite: "rannte", participle: "gerannt", auxiliary: "sein", example: "Ich bin zum Bus gerannt.", priority: 1 },
  { infinitive: "schlagen", pattern: "a - u - a", translation: "бить; ударять", preterite: "schlug", participle: "geschlagen", auxiliary: "haben", example: "Er hat mit der Faust auf den Tisch geschlagen.", priority: 1 },
  { infinitive: "können", pattern: "ö - o - o", translation: "мочь; уметь", preterite: "konnte", participle: "gekonnt", auxiliary: "haben", example: "Als Vollverb: Das habe ich früher besser gekonnt.", priority: 2, modal: true },
  { infinitive: "mögen", pattern: "ö - o - o", translation: "любить; нравиться", preterite: "mochte", participle: "gemocht", auxiliary: "haben", example: "Ich habe diesen Film sehr gemocht.", priority: 2, modal: true },
  { infinitive: "müssen", pattern: "ü - u - u", translation: "быть должным; быть вынужденным", preterite: "musste", participle: "gemusst", auxiliary: "haben", example: "Als Vollverb: Ich habe heute nicht gemusst.", priority: 2, modal: true },
  { infinitive: "sollen", pattern: "o - o - o", translation: "быть должным; следовать указанию", preterite: "sollte", participle: "gesollt", auxiliary: "haben", example: "Als Vollverb: Das habe ich nicht gesollt.", priority: 2, modal: true },
  { infinitive: "wollen", pattern: "o - o - o", translation: "хотеть", preterite: "wollte", participle: "gewollt", auxiliary: "haben", example: "Das habe ich nicht gewollt.", priority: 2, modal: true },
];
