window.WORDS = [
  {
    "id": 1,
    "sentence": "Ich gehe spazieren, {{c1::obwohl}} es regnet.",
    "blank": "Ich gehe spazieren, _____ es regnet.",
    "revealed": "Ich gehe spazieren, obwohl es regnet.",
    "ru": "Я иду гулять, хотя идёт дождь.",
    "grammar": "obwohl + глагол в конце",
    "translation": "хотя, несмотря на то что",
    "pos": "Konjunktion",
    "base": "obwohl",
    "target": "obwohl"
  },
  {
    "id": 2,
    "sentence": "Ich muss meine Fahrstunde {{c1::absagen}}.",
    "blank": "Ich muss meine Fahrstunde _____.",
    "revealed": "Ich muss meine Fahrstunde absagen.",
    "ru": "Мне нужно отменить урок вождения.",
    "grammar": "absagen · sagte ab · hat abgesagt",
    "translation": "отменять",
    "pos": "Verb",
    "base": "absagen",
    "target": "absagen"
  },
  {
    "id": 3,
    "sentence": "Was ist der {{c1::Grund}}?",
    "blank": "Was ist der _____?",
    "revealed": "Was ist der Grund?",
    "ru": "В чём причина?",
    "grammar": "der Grund · die Gründe",
    "translation": "причина, основание",
    "pos": "Substantiv",
    "base": "der Grund",
    "target": "Grund"
  },
  {
    "id": 4,
    "sentence": "Das ist nicht {{c1::notwendig}}.",
    "blank": "Das ist nicht _____.",
    "revealed": "Das ist nicht notwendig.",
    "ru": "Это не обязательно / не необходимо.",
    "grammar": "",
    "translation": "необходимый, нужный",
    "pos": "Adjektiv",
    "base": "notwendig",
    "target": "notwendig"
  },
  {
    "id": 5,
    "sentence": "Es regnet. {{c1::Trotzdem}} gehe ich spazieren.",
    "blank": "Es regnet. _____ gehe ich spazieren.",
    "revealed": "Es regnet. Trotzdem gehe ich spazieren.",
    "ru": "Идёт дождь. Несмотря на это, я иду гулять.",
    "grammar": "",
    "translation": "несмотря на это, всё же",
    "pos": "Adverb",
    "base": "trotzdem",
    "target": "Trotzdem"
  },
  {
    "id": 6,
    "sentence": "Können wir den Termin auf Freitag {{c1::verschieben}}?",
    "blank": "Können wir den Termin auf Freitag _____?",
    "revealed": "Können wir den Termin auf Freitag verschieben?",
    "ru": "Можем перенести встречу на пятницу?",
    "grammar": "verschieben · verschob · hat verschoben",
    "translation": "переносить",
    "pos": "Verb",
    "base": "verschieben",
    "target": "verschieben"
  },
  {
    "id": 7,
    "sentence": "Das ist eine schwere {{c1::Entscheidung}}.",
    "blank": "Das ist eine schwere _____.",
    "revealed": "Das ist eine schwere Entscheidung.",
    "ru": "Это трудное решение.",
    "grammar": "die Entscheidung · die Entscheidungen",
    "translation": "решение",
    "pos": "Substantiv",
    "base": "die Entscheidung",
    "target": "Entscheidung"
  },
  {
    "id": 8,
    "sentence": "{{c1::Wahrscheinlich}} komme ich später.",
    "blank": "_____ komme ich später.",
    "revealed": "Wahrscheinlich komme ich später.",
    "ru": "Вероятно, я приду позже.",
    "grammar": "",
    "translation": "вероятно",
    "pos": "Adverb/Adjektiv",
    "base": "wahrscheinlich",
    "target": "Wahrscheinlich"
  },
  {
    "id": 9,
    "sentence": "Ich kann mich nicht {{c1::entscheiden}}.",
    "blank": "Ich kann mich nicht _____.",
    "revealed": "Ich kann mich nicht entscheiden.",
    "ru": "Я не могу решиться / сделать выбор.",
    "grammar": "sich entscheiden · entschied sich · hat sich entschieden",
    "translation": "решаться, принимать решение",
    "pos": "Verb",
    "base": "sich entscheiden",
    "target": "entscheiden"
  },
  {
    "id": 10,
    "sentence": "Unsere Taschen sind {{c1::ähnlich}}.",
    "blank": "Unsere Taschen sind _____.",
    "revealed": "Unsere Taschen sind ähnlich.",
    "ru": "Наши сумки похожи.",
    "grammar": "",
    "translation": "похожий",
    "pos": "Adjektiv",
    "base": "ähnlich",
    "target": "ähnlich"
  },
  {
    "id": 11,
    "sentence": "Ich bin müde, {{c1::deshalb}} gehe ich nach Hause.",
    "blank": "Ich bin müde, _____ gehe ich nach Hause.",
    "revealed": "Ich bin müde, deshalb gehe ich nach Hause.",
    "ru": "Я устала, поэтому иду домой.",
    "grammar": "deshalb = поэтому",
    "translation": "поэтому",
    "pos": "Adverb",
    "base": "deshalb",
    "target": "deshalb"
  },
  {
    "id": 12,
    "sentence": "Ich {{c1::schlage}} Samstag {{c1::vor}}.",
    "blank": "Ich _____ Samstag _____.",
    "revealed": "Ich schlage Samstag vor.",
    "ru": "Я предлагаю субботу.",
    "grammar": "vorschlagen · du schlägst vor / er schlägt vor · schlug vor · hat vorgeschlagen",
    "translation": "предлагать",
    "pos": "Verb",
    "base": "vorschlagen",
    "target": "schlage / vor"
  },
  {
    "id": 13,
    "sentence": "Mein {{c1::Antrag}} ist noch nicht fertig.",
    "blank": "Mein _____ ist noch nicht fertig.",
    "revealed": "Mein Antrag ist noch nicht fertig.",
    "ru": "Моё заявление ещё не готово.",
    "grammar": "der Antrag · die Anträge",
    "translation": "заявление, заявка",
    "pos": "Substantiv",
    "base": "der Antrag",
    "target": "Antrag"
  },
  {
    "id": 14,
    "sentence": "Ich bin für die Prüfung {{c1::bereit}}.",
    "blank": "Ich bin für die Prüfung _____.",
    "revealed": "Ich bin für die Prüfung bereit.",
    "ru": "Я готова к экзамену.",
    "grammar": "bereit ≠ breit",
    "translation": "готовый",
    "pos": "Adjektiv",
    "base": "bereit",
    "target": "bereit"
  },
  {
    "id": 15,
    "sentence": "Ich brauche Brot und {{c1::außerdem}} Milch.",
    "blank": "Ich brauche Brot und _____ Milch.",
    "revealed": "Ich brauche Brot und außerdem Milch.",
    "ru": "Мне нужен хлеб, а кроме того молоко.",
    "grammar": "",
    "translation": "кроме того",
    "pos": "Adverb",
    "base": "außerdem",
    "target": "außerdem"
  },
  {
    "id": 16,
    "sentence": "Ich {{c1::vermeide}} den Supermarkt am Samstag.",
    "blank": "Ich _____ den Supermarkt am Samstag.",
    "revealed": "Ich vermeide den Supermarkt am Samstag.",
    "ru": "Я избегаю супермаркета по субботам.",
    "grammar": "vermeiden · vermied · hat vermieden",
    "translation": "избегать",
    "pos": "Verb",
    "base": "vermeiden",
    "target": "vermeide"
  },
  {
    "id": 17,
    "sentence": "Die {{c1::Frist}} endet am Freitag.",
    "blank": "Die _____ endet am Freitag.",
    "revealed": "Die Frist endet am Freitag.",
    "ru": "Срок заканчивается в пятницу.",
    "grammar": "die Frist · die Fristen",
    "translation": "срок",
    "pos": "Substantiv",
    "base": "die Frist",
    "target": "Frist"
  },
  {
    "id": 18,
    "sentence": "Die Woche war sehr {{c1::anstrengend}}.",
    "blank": "Die Woche war sehr _____.",
    "revealed": "Die Woche war sehr anstrengend.",
    "ru": "Неделя была очень утомительной.",
    "grammar": "",
    "translation": "утомительный, напряжённый",
    "pos": "Adjektiv",
    "base": "anstrengend",
    "target": "anstrengend"
  },
  {
    "id": 19,
    "sentence": "Ich trinke keinen Tee, {{c1::sondern}} Kaffee.",
    "blank": "Ich trinke keinen Tee, _____ Kaffee.",
    "revealed": "Ich trinke keinen Tee, sondern Kaffee.",
    "ru": "Я пью не чай, а кофе.",
    "grammar": "nicht ..., sondern ...",
    "translation": "а, а наоборот",
    "pos": "Konjunktion",
    "base": "sondern",
    "target": "sondern"
  },
  {
    "id": 20,
    "sentence": "Ich {{c1::bereite}} mich auf die Prüfung {{c1::vor}}.",
    "blank": "Ich _____ mich auf die Prüfung _____.",
    "revealed": "Ich bereite mich auf die Prüfung vor.",
    "ru": "Я готовлюсь к экзамену.",
    "grammar": "sich vorbereiten auf + Akk. · bereitete sich vor · hat sich vorbereitet",
    "translation": "готовиться к",
    "pos": "Verb",
    "base": "sich vorbereiten auf + Akk.",
    "target": "bereite / vor"
  },
  {
    "id": 21,
    "sentence": "Seine Bemerkung war ziemlich {{c1::ärgerlich}}.",
    "blank": "Seine Bemerkung war ziemlich _____.",
    "revealed": "Seine Bemerkung war ziemlich ärgerlich.",
    "ru": "Его замечание было довольно раздражающим.",
    "grammar": "",
    "translation": "раздражающий, досадный",
    "pos": "Adjektiv",
    "base": "ärgerlich",
    "target": "ärgerlich"
  },
  {
    "id": 22,
    "sentence": "Das kleine Café ist sehr {{c1::gemütlich}}.",
    "blank": "Das kleine Café ist sehr _____.",
    "revealed": "Das kleine Café ist sehr gemütlich.",
    "ru": "Это маленькое кафе очень уютное.",
    "grammar": "",
    "translation": "уютный, комфортный",
    "pos": "Adjektiv",
    "base": "gemütlich",
    "target": "gemütlich"
  },
  {
    "id": 23,
    "sentence": "Ich war {{c1::baff}}, als ich die Nachricht gelesen habe.",
    "blank": "Ich war _____, als ich die Nachricht gelesen habe.",
    "revealed": "Ich war baff, als ich die Nachricht gelesen habe.",
    "ru": "Я была ошеломлена, когда прочитала сообщение.",
    "grammar": "",
    "translation": "ошеломлённый, поражённый",
    "pos": "Adjektiv",
    "base": "baff",
    "target": "baff"
  },
  {
    "id": 24,
    "sentence": "Nach dem Urlaub hatte ich starkes {{c1::Fernweh}}.",
    "blank": "Nach dem Urlaub hatte ich starkes _____.",
    "revealed": "Nach dem Urlaub hatte ich starkes Fernweh.",
    "ru": "После отпуска мне очень хотелось снова куда-нибудь далеко уехать.",
    "grammar": "das Fernweh · kein Plural",
    "translation": "тяга к дальним странам, тоска по путешествиям",
    "pos": "Substantiv",
    "base": "das Fernweh",
    "target": "Fernweh"
  },
  {
    "id": 25,
    "sentence": "Nach dem Urlaub fühlte ich mich wieder {{c1::glücklich}}.",
    "blank": "Nach dem Urlaub fühlte ich mich wieder _____.",
    "revealed": "Nach dem Urlaub fühlte ich mich wieder glücklich.",
    "ru": "После отпуска я снова чувствовала себя счастливой.",
    "grammar": "",
    "translation": "счастливый",
    "pos": "Adjektiv",
    "base": "glücklich",
    "target": "glücklich"
  },
  {
    "id": 26,
    "sentence": "Sie ist mit dem Ergebnis {{c1::unzufrieden}}.",
    "blank": "Sie ist mit dem Ergebnis _____.",
    "revealed": "Sie ist mit dem Ergebnis unzufrieden.",
    "ru": "Она недовольна результатом.",
    "grammar": "unzufrieden mit + Dat.",
    "translation": "недовольный",
    "pos": "Adjektiv",
    "base": "unzufrieden",
    "target": "unzufrieden"
  },
  {
    "id": 27,
    "sentence": "Bist du mit deiner Entscheidung {{c1::zufrieden}}?",
    "blank": "Bist du mit deiner Entscheidung _____?",
    "revealed": "Bist du mit deiner Entscheidung zufrieden?",
    "ru": "Ты довольна своим решением?",
    "grammar": "zufrieden mit + Dat.",
    "translation": "довольный",
    "pos": "Adjektiv",
    "base": "zufrieden",
    "target": "zufrieden"
  },
  {
    "id": 28,
    "sentence": "Sie hat ein {{c1::Ehrenamt}}.",
    "blank": "Sie hat ein _____.",
    "revealed": "Sie hat ein Ehrenamt.",
    "ru": "Она занимается волонтёрской / общественной деятельностью.",
    "grammar": "das Ehrenamt · die Ehrenämter",
    "translation": "волонтёрская, общественная деятельность",
    "pos": "Substantiv",
    "base": "das Ehrenamt",
    "target": "Ehrenamt"
  },
  {
    "id": 29,
    "sentence": "Wir können nicht {{c1::gleichzeitig}} arbeiten und telefonieren.",
    "blank": "Wir können nicht _____ arbeiten und telefonieren.",
    "revealed": "Wir können nicht gleichzeitig arbeiten und telefonieren.",
    "ru": "Мы не можем одновременно работать и разговаривать по телефону.",
    "grammar": "",
    "translation": "одновременно",
    "pos": "Adverb",
    "base": "gleichzeitig",
    "target": "gleichzeitig"
  },
  {
    "id": 30,
    "sentence": "Mein Großvater ist vor zwei Jahren {{c1::gestorben}}.",
    "blank": "Mein Großvater ist vor zwei Jahren _____.",
    "revealed": "Mein Großvater ist vor zwei Jahren gestorben.",
    "ru": "Мой дедушка умер два года назад.",
    "grammar": "sterben · starb · ist gestorben",
    "translation": "умирать",
    "pos": "Verb",
    "base": "sterben",
    "target": "gestorben"
  },
  {
    "id": 31,
    "sentence": "Ich habe {{c1::nirgends}} meine Schlüssel gefunden.",
    "blank": "Ich habe _____ meine Schlüssel gefunden.",
    "revealed": "Ich habe nirgends meine Schlüssel gefunden.",
    "ru": "Я нигде не нашла свои ключи.",
    "grammar": "",
    "translation": "нигде",
    "pos": "Adverb",
    "base": "nirgends",
    "target": "nirgends"
  },
  {
    "id": 32,
    "sentence": "Du musst selbst {{c1::bestimmen}}, was du machen möchtest.",
    "blank": "Du musst selbst _____, was du machen möchtest.",
    "revealed": "Du musst selbst bestimmen, was du machen möchtest.",
    "ru": "Ты должна сама решить, что хочешь делать.",
    "grammar": "bestimmen · bestimmte · hat bestimmt",
    "translation": "определять, решать",
    "pos": "Verb",
    "base": "bestimmen",
    "target": "bestimmen"
  },
  {
    "id": 33,
    "sentence": "Keine Sorge, die Atmosphäre hier ist ganz {{c1::locker}}.",
    "blank": "Keine Sorge, die Atmosphäre hier ist ganz _____.",
    "revealed": "Keine Sorge, die Atmosphäre hier ist ganz locker.",
    "ru": "Не переживай, здесь очень непринуждённая атмосфера.",
    "grammar": "",
    "translation": "непринуждённый, расслабленный",
    "pos": "Adjektiv",
    "base": "locker",
    "target": "locker"
  },
  {
    "id": 34,
    "sentence": "Die beiden hatten gestern einen großen {{c1::Streit}}.",
    "blank": "Die beiden hatten gestern einen großen _____.",
    "revealed": "Die beiden hatten gestern einen großen Streit.",
    "ru": "Вчера они сильно поссорились.",
    "grammar": "der Streit · die Streite",
    "translation": "ссора, конфликт",
    "pos": "Substantiv",
    "base": "der Streit",
    "target": "Streit"
  },
  {
    "id": 35,
    "sentence": "Ich habe großes {{c1::Heimweh}}, wenn ich lange nicht zu Hause bin.",
    "blank": "Ich habe großes _____, wenn ich lange nicht zu Hause bin.",
    "revealed": "Ich habe großes Heimweh, wenn ich lange nicht zu Hause bin.",
    "ru": "Я сильно скучаю по дому, когда долго не бываю дома.",
    "grammar": "das Heimweh · kein Plural",
    "translation": "тоска по дому",
    "pos": "Substantiv",
    "base": "das Heimweh",
    "target": "Heimweh"
  },
  {
    "id": 36,
    "sentence": "Er war {{c1::zornig}} auf mich.",
    "blank": "Er war _____ auf mich.",
    "revealed": "Er war zornig auf mich.",
    "ru": "Он был настолько разгневан, что едва мог говорить.",
    "grammar": "",
    "translation": "разгневанный, очень злой",
    "pos": "Adjektiv",
    "base": "zornig",
    "target": "zornig"
  },
  {
    "id": 37,
    "sentence": "Das Kind begann plötzlich zu {{c1::weinen}}.",
    "blank": "Das Kind begann plötzlich zu _____.",
    "revealed": "Das Kind begann plötzlich zu weinen.",
    "ru": "Ребёнок внезапно начал плакать.",
    "grammar": "weinen · weinte · hat geweint",
    "translation": "плакать",
    "pos": "Verb",
    "base": "weinen",
    "target": "weinen"
  },
  {
    "id": 38,
    "sentence": "{{c1::Vertrauen}} ist sehr wichtig.",
    "blank": "_____ ist sehr wichtig.",
    "revealed": "Vertrauen ist sehr wichtig.",
    "ru": "Доверие — основа любых хороших отношений.",
    "grammar": "das Vertrauen · kein Plural",
    "translation": "доверие",
    "pos": "Substantiv",
    "base": "das Vertrauen",
    "target": "Vertrauen"
  },
  {
    "id": 39,
    "sentence": "Das ist {{c1::lächerlich}}.",
    "blank": "Das ist _____.",
    "revealed": "Das ist lächerlich.",
    "ru": "Его поведение было настолько нелепым, что все были вынуждены смеяться.",
    "grammar": "",
    "translation": "смешной, нелепый, смехотворный",
    "pos": "Adjektiv",
    "base": "lächerlich",
    "target": "lächerlich"
  },
  {
    "id": 40,
    "sentence": "Ich {{c1::bewundere}} meine Mutter.",
    "blank": "Ich _____ meine Mutter.",
    "revealed": "Ich bewundere meine Mutter.",
    "ru": "Я восхищаюсь людьми, которые никогда не сдаются.",
    "grammar": "bewundern · bewunderte · hat bewundert",
    "translation": "восхищаться",
    "pos": "Verb",
    "base": "bewundern",
    "target": "bewundere"
  },
  {
    "id": 41,
    "sentence": "Der Film war sehr {{c1::romantisch}}.",
    "blank": "Der Film war sehr _____.",
    "revealed": "Der Film war sehr romantisch.",
    "ru": "Фильм был очень романтичным.",
    "grammar": "",
    "translation": "романтичный",
    "pos": "Adjektiv",
    "base": "romantisch",
    "target": "romantisch"
  },
  {
    "id": 42,
    "sentence": "Das ist {{c1::erstaunlich}}.",
    "blank": "Das ist _____.",
    "revealed": "Das ist erstaunlich.",
    "ru": "Удивительно, как быстро проходит время.",
    "grammar": "",
    "translation": "удивительный, поразительный",
    "pos": "Adjektiv",
    "base": "erstaunlich",
    "target": "erstaunlich"
  },
  {
    "id": 43,
    "sentence": "Musik kann mich schnell {{c1::beruhigen}}.",
    "blank": "Musik kann mich schnell _____.",
    "revealed": "Musik kann mich schnell beruhigen.",
    "ru": "Музыка может быстро меня успокоить.",
    "grammar": "beruhigen · beruhigte · hat beruhigt",
    "translation": "успокаивать",
    "pos": "Verb",
    "base": "beruhigen",
    "target": "beruhigen"
  },
  {
    "id": 44,
    "sentence": "Am Wochenende möchte ich mich einfach {{c1::entspannen}}.",
    "blank": "Am Wochenende möchte ich mich einfach _____.",
    "revealed": "Am Wochenende möchte ich mich einfach entspannen.",
    "ru": "На выходных я просто хочу расслабиться.",
    "grammar": "sich entspannen · entspannte sich · hat sich entspannt",
    "translation": "расслабляться, отдыхать",
    "pos": "Verb",
    "base": "sich entspannen",
    "target": "entspannen"
  },
  {
    "id": 45,
    "sentence": "Er hat versucht, mich zu {{c1::betrügen}}.",
    "blank": "Er hat versucht, mich zu _____.",
    "revealed": "Er hat versucht, mich zu betrügen.",
    "ru": "Он пытался меня обмануть.",
    "grammar": "betrügen · betrog · hat betrogen",
    "translation": "обманывать, мошенничать",
    "pos": "Verb",
    "base": "betrügen",
    "target": "betrügen"
  },
  {
    "id": 46,
    "sentence": "Ich möchte mich über den schlechten Service {{c1::beschweren}}.",
    "blank": "Ich möchte mich über den schlechten Service _____.",
    "revealed": "Ich möchte mich über den schlechten Service beschweren.",
    "ru": "Я хочу пожаловаться на плохое обслуживание.",
    "grammar": "sich beschweren über + Akk. · beschwerte sich · hat sich beschwert",
    "translation": "жаловаться на",
    "pos": "Verb",
    "base": "sich beschweren über + Akk.",
    "target": "beschweren"
  },
  {
    "id": 47,
    "sentence": "Manchmal habe ich {{c1::Weltschmerz}}.",
    "blank": "Manchmal habe ich _____.",
    "revealed": "Manchmal habe ich Weltschmerz.",
    "ru": "Многие люди испытывают мировую тоску, когда видят, что происходит в мире.",
    "grammar": "der Weltschmerz · kein Plural",
    "translation": "мировая тоска, печаль из-за несовершенства мира",
    "pos": "Substantiv",
    "base": "der Weltschmerz",
    "target": "Weltschmerz"
  },
  {
    "id": 48,
    "sentence": "Vor einer Reise spüre ich immer große {{c1::Vorfreude}}.",
    "blank": "Vor einer Reise spüre ich immer große _____.",
    "revealed": "Vor einer Reise spüre ich immer große Vorfreude.",
    "ru": "Перед поездкой я всегда испытываю приятное предвкушение.",
    "grammar": "die Vorfreude · kein Plural",
    "translation": "предвкушение, радостное ожидание",
    "pos": "Substantiv",
    "base": "die Vorfreude",
    "target": "Vorfreude"
  },
  {
    "id": 49,
    "sentence": "Er hat {{c1::Schadenfreude}}.",
    "blank": "Er hat _____.",
    "revealed": "Er hat Schadenfreude.",
    "ru": "Он испытал немного злорадства, когда его конкурент проиграл.",
    "grammar": "die Schadenfreude · kein Plural",
    "translation": "злорадство",
    "pos": "Substantiv",
    "base": "die Schadenfreude",
    "target": "Schadenfreude"
  },
  {
    "id": 50,
    "sentence": "Nach dem Umzug fühlte sie sich {{c1::mutterseelenallein}}.",
    "blank": "Nach dem Umzug fühlte sie sich _____.",
    "revealed": "Nach dem Umzug fühlte sie sich mutterseelenallein.",
    "ru": "После переезда она чувствовала себя совершенно одинокой.",
    "grammar": "",
    "translation": "совершенно одинокий, совсем один",
    "pos": "Adjektiv",
    "base": "mutterseelenallein",
    "target": "mutterseelenallein"
  },
  {
    "id": 51,
    "sentence": "Sie ist ein sehr {{c1::warmherziger}} Mensch.",
    "blank": "Sie ist ein sehr _____ Mensch.",
    "revealed": "Sie ist ein sehr warmherziger Mensch.",
    "ru": "Она очень душевный и добрый человек.",
    "grammar": "",
    "translation": "душевный, сердечный, добрый",
    "pos": "Adjektiv",
    "base": "warmherzig",
    "target": "warmherziger"
  },
  {
    "id": 52,
    "sentence": "Er war völlig {{c1::verzweifelt}}, weil er keine Lösung gefunden hatte.",
    "blank": "Er war völlig _____, weil er keine Lösung gefunden hatte.",
    "revealed": "Er war völlig verzweifelt, weil er keine Lösung gefunden hatte.",
    "ru": "Он был совершенно отчаявшимся, потому что не нашёл решения.",
    "grammar": "",
    "translation": "отчаявшийся, в отчаянии",
    "pos": "Adjektiv",
    "base": "verzweifelt",
    "target": "verzweifelt"
  },
  {
    "id": 53,
    "sentence": "Er reagierte völlig {{c1::gleichgültig}} auf die Nachricht.",
    "blank": "Er reagierte völlig _____ auf die Nachricht.",
    "revealed": "Er reagierte völlig gleichgültig auf die Nachricht.",
    "ru": "Он совершенно безразлично отреагировал на сообщение.",
    "grammar": "gleichgültig gegenüber + Dat.",
    "translation": "безразличный, равнодушный",
    "pos": "Adjektiv",
    "base": "gleichgültig",
    "target": "gleichgültig"
  },
  {
    "id": 54,
    "sentence": "Sie sieht {{c1::besorgt}} aus.",
    "blank": "Sie sieht _____ aus.",
    "revealed": "Sie sieht besorgt aus.",
    "ru": "Она выглядит обеспокоенной.",
    "grammar": "",
    "translation": "обеспокоенный, встревоженный",
    "pos": "Adjektiv",
    "base": "besorgt",
    "target": "besorgt"
  },
  {
    "id": 55,
    "sentence": "Das Kind war {{c1::ängstlich}}, als es allein im Zimmer war.",
    "blank": "Das Kind war _____, als es allein im Zimmer war.",
    "revealed": "Das Kind war ängstlich, als es allein im Zimmer war.",
    "ru": "Ребёнку было страшно, когда он был один в комнате.",
    "grammar": "",
    "translation": "боязливый, испуганный",
    "pos": "Adjektiv",
    "base": "ängstlich",
    "target": "ängstlich"
  },
  {
    "id": 56,
    "sentence": "Vor meinem ersten Arbeitstag war ich sehr {{c1::aufgeregt}}.",
    "blank": "Vor meinem ersten Arbeitstag war ich sehr _____.",
    "revealed": "Vor meinem ersten Arbeitstag war ich sehr aufgeregt.",
    "ru": "Перед первым рабочим днём я очень волновалась.",
    "grammar": "",
    "translation": "взволнованный, возбуждённый",
    "pos": "Adjektiv",
    "base": "aufgeregt",
    "target": "aufgeregt"
  },
  {
    "id": 57,
    "sentence": "Ich bin vom Film {{c1::enttäuscht}}.",
    "blank": "Ich bin vom Film _____.",
    "revealed": "Ich bin vom Film enttäuscht.",
    "ru": "Я разочарована фильмом.",
    "grammar": "",
    "translation": "разочарованный",
    "pos": "Adjektiv",
    "base": "enttäuscht",
    "target": "enttäuscht"
  },
  {
    "id": 58,
    "sentence": "Es war mir {{c1::peinlich}}, vor allen Leuten zu sprechen.",
    "blank": "Es war mir _____, vor allen Leuten zu sprechen.",
    "revealed": "Es war mir peinlich, vor allen Leuten zu sprechen.",
    "ru": "Мне было неловко говорить перед всеми.",
    "grammar": "",
    "translation": "неловкий, постыдный",
    "pos": "Adjektiv",
    "base": "peinlich",
    "target": "peinlich"
  },
  {
    "id": 59,
    "sentence": "Sei bitte {{c1::ehrlich}} zu mir.",
    "blank": "Sei bitte _____ zu mir.",
    "revealed": "Sei bitte ehrlich zu mir.",
    "ru": "Пожалуйста, будь со мной честна.",
    "grammar": "",
    "translation": "честный",
    "pos": "Adjektiv",
    "base": "ehrlich",
    "target": "ehrlich"
  }
];
