window.WORDS = [
  {
    "id": 1,
    "sentence": "Ich gehe spazieren, {{c1::obwohl}} es regnet.",
    "blank": "Ich gehe spazieren, _____ es regnet.",
    "revealed": "Ich gehe spazieren, obwohl es regnet.",
    "ru": "Я иду гулять, хотя идёт дождь.",
    "grammar": "obwohl + глагол в конце",
    "translation": "хотя, несмотря на то что",
    "pos": "Konjunktion",
    "base": "obwohl",
    "target": "obwohl"
  },
  {
    "id": 2,
    "sentence": "Ich muss meine Fahrstunde {{c1::absagen}}.",
    "blank": "Ich muss meine Fahrstunde _____.",
    "revealed": "Ich muss meine Fahrstunde absagen.",
    "ru": "Мне нужно отменить урок вождения.",
    "grammar": "absagen · sagte ab · hat abgesagt",
    "translation": "отменять",
    "pos": "Verb",
    "base": "absagen",
    "target": "absagen"
  },
  {
    "id": 3,
    "sentence": "Was ist der {{c1::Grund}}?",
    "blank": "Was ist der _____?",
    "revealed": "Was ist der Grund?",
    "ru": "В чём причина?",
    "grammar": "der Grund · die Gründe",
    "translation": "причина, основание",
    "pos": "Substantiv",
    "base": "der Grund",
    "target": "Grund"
  },
  {
    "id": 4,
    "sentence": "Das ist nicht {{c1::notwendig}}.",
    "blank": "Das ist nicht _____.",
    "revealed": "Das ist nicht notwendig.",
    "ru": "Это не обязательно / не необходимо.",
    "grammar": "",
    "translation": "необходимый, нужный",
    "pos": "Adjektiv",
    "base": "notwendig",
    "target": "notwendig"
  },
  {
    "id": 5,
    "sentence": "Es regnet. {{c1::Trotzdem}} gehe ich spazieren.",
    "blank": "Es regnet. _____ gehe ich spazieren.",
    "revealed": "Es regnet. Trotzdem gehe ich spazieren.",
    "ru": "Идёт дождь. Несмотря на это, я иду гулять.",
    "grammar": "",
    "translation": "несмотря на это, всё же",
    "pos": "Adverb",
    "base": "trotzdem",
    "target": "Trotzdem"
  },
  {
    "id": 6,
    "sentence": "Können wir den Termin auf Freitag {{c1::verschieben}}?",
    "blank": "Können wir den Termin auf Freitag _____?",
    "revealed": "Können wir den Termin auf Freitag verschieben?",
    "ru": "Можем перенести встречу на пятницу?",
    "grammar": "verschieben · verschob · hat verschoben",
    "translation": "переносить",
    "pos": "Verb",
    "base": "verschieben",
    "target": "verschieben"
  },
  {
    "id": 7,
    "sentence": "Das ist eine schwere {{c1::Entscheidung}}.",
    "blank": "Das ist eine schwere _____.",
    "revealed": "Das ist eine schwere Entscheidung.",
    "ru": "Это трудное решение.",
    "grammar": "die Entscheidung · die Entscheidungen",
    "translation": "решение",
    "pos": "Substantiv",
    "base": "die Entscheidung",
    "target": "Entscheidung"
  },
  {
    "id": 8,
    "sentence": "{{c1::Wahrscheinlich}} komme ich später.",
    "blank": "_____ komme ich später.",
    "revealed": "Wahrscheinlich komme ich später.",
    "ru": "Вероятно, я приду позже.",
    "grammar": "",
    "translation": "вероятно",
    "pos": "Adverb/Adjektiv",
    "base": "wahrscheinlich",
    "target": "Wahrscheinlich"
  },
  {
    "id": 9,
    "sentence": "Ich kann mich nicht {{c1::entscheiden}}.",
    "blank": "Ich kann mich nicht _____.",
    "revealed": "Ich kann mich nicht entscheiden.",
    "ru": "Я не могу решиться / сделать выбор.",
    "grammar": "sich entscheiden · entschied sich · hat sich entschieden",
    "translation": "решаться, принимать решение",
    "pos": "Verb",
    "base": "sich entscheiden",
    "target": "entscheiden"
  },
  {
    "id": 10,
    "sentence": "Unsere Taschen sind {{c1::ähnlich}}.",
    "blank": "Unsere Taschen sind _____.",
    "revealed": "Unsere Taschen sind ähnlich.",
    "ru": "Наши сумки похожи.",
    "grammar": "",
    "translation": "похожий",
    "pos": "Adjektiv",
    "base": "ähnlich",
    "target": "ähnlich"
  },
  {
    "id": 11,
    "sentence": "Ich bin müde, {{c1::deshalb}} gehe ich nach Hause.",
    "blank": "Ich bin müde, _____ gehe ich nach Hause.",
    "revealed": "Ich bin müde, deshalb gehe ich nach Hause.",
    "ru": "Я устала, поэтому иду домой.",
    "grammar": "deshalb = поэтому",
    "translation": "поэтому",
    "pos": "Adverb",
    "base": "deshalb",
    "target": "deshalb"
  },
  {
    "id": 12,
    "sentence": "Ich {{c1::schlage}} Samstag {{c1::vor}}.",
    "blank": "Ich _____ Samstag _____.",
    "revealed": "Ich schlage Samstag vor.",
    "ru": "Я предлагаю субботу.",
    "grammar": "vorschlagen · du schlägst vor / er schlägt vor · schlug vor · hat vorgeschlagen",
    "translation": "предлагать",
    "pos": "Verb",
    "base": "vorschlagen",
    "target": "schlage / vor"
  },
  {
    "id": 13,
    "sentence": "Mein {{c1::Antrag}} ist noch nicht fertig.",
    "blank": "Mein _____ ist noch nicht fertig.",
    "revealed": "Mein Antrag ist noch nicht fertig.",
    "ru": "Моё заявление ещё не готово.",
    "grammar": "der Antrag · die Anträge",
    "translation": "заявление, заявка",
    "pos": "Substantiv",
    "base": "der Antrag",
    "target": "Antrag"
  },
  {
    "id": 14,
    "sentence": "Ich bin für die Prüfung {{c1::bereit}}.",
    "blank": "Ich bin für die Prüfung _____.",
    "revealed": "Ich bin für die Prüfung bereit.",
    "ru": "Я готова к экзамену.",
    "grammar": "bereit ≠ breit",
    "translation": "готовый",
    "pos": "Adjektiv",
    "base": "bereit",
    "target": "bereit"
  },
  {
    "id": 15,
    "sentence": "Ich brauche Brot und {{c1::außerdem}} Milch.",
    "blank": "Ich brauche Brot und _____ Milch.",
    "revealed": "Ich brauche Brot und außerdem Milch.",
    "ru": "Мне нужен хлеб, а кроме того молоко.",
    "grammar": "",
    "translation": "кроме того",
    "pos": "Adverb",
    "base": "außerdem",
    "target": "außerdem"
  },
  {
    "id": 16,
    "sentence": "Ich {{c1::vermeide}} den Supermarkt am Samstag.",
    "blank": "Ich _____ den Supermarkt am Samstag.",
    "revealed": "Ich vermeide den Supermarkt am Samstag.",
    "ru": "Я избегаю супермаркета по субботам.",
    "grammar": "vermeiden · vermied · hat vermieden",
    "translation": "избегать",
    "pos": "Verb",
    "base": "vermeiden",
    "target": "vermeide"
  },
  {
    "id": 17,
    "sentence": "Die {{c1::Frist}} endet am Freitag.",
    "blank": "Die _____ endet am Freitag.",
    "revealed": "Die Frist endet am Freitag.",
    "ru": "Срок заканчивается в пятницу.",
    "grammar": "die Frist · die Fristen",
    "translation": "срок",
    "pos": "Substantiv",
    "base": "die Frist",
    "target": "Frist"
  },
  {
    "id": 18,
    "sentence": "Die Woche war sehr {{c1::anstrengend}}.",
    "blank": "Die Woche war sehr _____.",
    "revealed": "Die Woche war sehr anstrengend.",
    "ru": "Неделя была очень утомительной.",
    "grammar": "",
    "translation": "утомительный, напряжённый",
    "pos": "Adjektiv",
    "base": "anstrengend",
    "target": "anstrengend"
  },
  {
    "id": 19,
    "sentence": "Ich trinke keinen Tee, {{c1::sondern}} Kaffee.",
    "blank": "Ich trinke keinen Tee, _____ Kaffee.",
    "revealed": "Ich trinke keinen Tee, sondern Kaffee.",
    "ru": "Я пью не чай, а кофе.",
    "grammar": "nicht ..., sondern ...",
    "translation": "а, а наоборот",
    "pos": "Konjunktion",
    "base": "sondern",
    "target": "sondern"
  },
  {
    "id": 20,
    "sentence": "Ich {{c1::bereite}} mich auf die Prüfung {{c1::vor}}.",
    "blank": "Ich _____ mich auf die Prüfung _____.",
    "revealed": "Ich bereite mich auf die Prüfung vor.",
    "ru": "Я готовлюсь к экзамену.",
    "grammar": "sich vorbereiten auf + Akk. · bereitete sich vor · hat sich vorbereitet",
    "translation": "готовиться к",
    "pos": "Verb",
    "base": "sich vorbereiten auf + Akk.",
    "target": "bereite / vor"
  },
  {
    "id": 21,
    "sentence": "Die Fahrt dauert {{c1::ungefähr}} zwei Stunden.",
    "blank": "Die Fahrt dauert _____ zwei Stunden.",
    "revealed": "Die Fahrt dauert ungefähr zwei Stunden.",
    "ru": "Поездка длится примерно два часа.",
    "grammar": "",
    "translation": "примерно",
    "pos": "Adverb",
    "base": "ungefähr",
    "target": "ungefähr"
  },
  {
    "id": 22,
    "sentence": "Wir {{c1::vereinbaren}} einen Termin.",
    "blank": "Wir _____ einen Termin.",
    "revealed": "Wir vereinbaren einen Termin.",
    "ru": "Мы договариваемся о встрече.",
    "grammar": "vereinbaren · vereinbarte · hat vereinbart",
    "translation": "договариваться, согласовывать",
    "pos": "Verb",
    "base": "vereinbaren",
    "target": "vereinbaren"
  },
  {
    "id": 23,
    "sentence": "Mein {{c1::Gehalt}} kommt am Monatsende.",
    "blank": "Mein _____ kommt am Monatsende.",
    "revealed": "Mein Gehalt kommt am Monatsende.",
    "ru": "Моя зарплата приходит в конце месяца.",
    "grammar": "das Gehalt · die Gehälter",
    "translation": "зарплата",
    "pos": "Substantiv",
    "base": "das Gehalt",
    "target": "Gehalt"
  },
  {
    "id": 24,
    "sentence": "Dieser Stuhl ist sehr {{c1::bequem}}.",
    "blank": "Dieser Stuhl ist sehr _____.",
    "revealed": "Dieser Stuhl ist sehr bequem.",
    "ru": "Этот стул очень удобный.",
    "grammar": "",
    "translation": "удобный",
    "pos": "Adjektiv",
    "base": "bequem",
    "target": "bequem"
  },
  {
    "id": 25,
    "sentence": "Ich brauche {{c1::mindestens}} acht Stunden Schlaf.",
    "blank": "Ich brauche _____ acht Stunden Schlaf.",
    "revealed": "Ich brauche mindestens acht Stunden Schlaf.",
    "ru": "Мне нужно минимум восемь часов сна.",
    "grammar": "",
    "translation": "как минимум",
    "pos": "Adverb",
    "base": "mindestens",
    "target": "mindestens"
  },
  {
    "id": 26,
    "sentence": "Ich {{c1::erwarte}} heute ein Paket.",
    "blank": "Ich _____ heute ein Paket.",
    "revealed": "Ich erwarte heute ein Paket.",
    "ru": "Я сегодня жду посылку.",
    "grammar": "erwarten · erwartete · hat erwartet",
    "translation": "ожидать",
    "pos": "Verb",
    "base": "erwarten",
    "target": "erwarte"
  },
  {
    "id": 27,
    "sentence": "Dein {{c1::Vorschlag}} ist gut.",
    "blank": "Dein _____ ist gut.",
    "revealed": "Dein Vorschlag ist gut.",
    "ru": "Твоё предложение хорошее.",
    "grammar": "der Vorschlag · die Vorschläge",
    "translation": "предложение",
    "pos": "Substantiv",
    "base": "der Vorschlag",
    "target": "Vorschlag"
  },
  {
    "id": 28,
    "sentence": "Diese Straße ist nachts {{c1::gefährlich}}.",
    "blank": "Diese Straße ist nachts _____.",
    "revealed": "Diese Straße ist nachts gefährlich.",
    "ru": "Эта улица ночью опасна.",
    "grammar": "",
    "translation": "опасный",
    "pos": "Adjektiv",
    "base": "gefährlich",
    "target": "gefährlich"
  },
  {
    "id": 29,
    "sentence": "{{c1::Eigentlich}} möchte ich heute zu Hause bleiben.",
    "blank": "_____ möchte ich heute zu Hause bleiben.",
    "revealed": "Eigentlich möchte ich heute zu Hause bleiben.",
    "ru": "Вообще-то я хочу сегодня остаться дома.",
    "grammar": "",
    "translation": "вообще-то, собственно",
    "pos": "Adverb",
    "base": "eigentlich",
    "target": "Eigentlich"
  },
  {
    "id": 30,
    "sentence": "Ich {{c1::beschwere}} mich über den Lärm.",
    "blank": "Ich _____ mich über den Lärm.",
    "revealed": "Ich beschwere mich über den Lärm.",
    "ru": "Я жалуюсь на шум.",
    "grammar": "sich beschweren über + Akk. · beschwerte sich · hat sich beschwert",
    "translation": "жаловаться на",
    "pos": "Verb",
    "base": "sich beschweren über + Akk.",
    "target": "beschwere"
  },
  {
    "id": 31,
    "sentence": "{{c1::Falls}} es regnet, bleibe ich zu Hause.",
    "blank": "_____ es regnet, bleibe ich zu Hause.",
    "revealed": "Falls es regnet, bleibe ich zu Hause.",
    "ru": "Если пойдёт дождь, я останусь дома.",
    "grammar": "",
    "translation": "если, в случае если",
    "pos": "Konjunktion",
    "base": "falls",
    "target": "Falls"
  },
  {
    "id": 32,
    "sentence": "Ich möchte die Prüfung {{c1::bestehen}}.",
    "blank": "Ich möchte die Prüfung _____.",
    "revealed": "Ich möchte die Prüfung bestehen.",
    "ru": "Я хочу сдать экзамен.",
    "grammar": "bestehen · bestand · hat bestanden",
    "translation": "сдать; состоять; существовать",
    "pos": "Verb",
    "base": "bestehen",
    "target": "bestehen"
  },
  {
    "id": 33,
    "sentence": "Das ist meine {{c1::Pflicht}}.",
    "blank": "Das ist meine _____.",
    "revealed": "Das ist meine Pflicht.",
    "ru": "Это моя обязанность.",
    "grammar": "die Pflicht · die Pflichten",
    "translation": "обязанность",
    "pos": "Substantiv",
    "base": "die Pflicht",
    "target": "Pflicht"
  },
  {
    "id": 34,
    "sentence": "Meine Straße ist nachts {{c1::ruhig}}.",
    "blank": "Meine Straße ist nachts _____.",
    "revealed": "Meine Straße ist nachts ruhig.",
    "ru": "Моя улица ночью тихая.",
    "grammar": "",
    "translation": "спокойный, тихий",
    "pos": "Adjektiv",
    "base": "ruhig",
    "target": "ruhig"
  },
  {
    "id": 35,
    "sentence": "Ich {{c1::lehne}} das Angebot {{c1::ab}}.",
    "blank": "Ich _____ das Angebot _____.",
    "revealed": "Ich lehne das Angebot ab.",
    "ru": "Я отклоняю предложение.",
    "grammar": "ablehnen · lehnte ab · hat abgelehnt",
    "translation": "отклонять, отказываться",
    "pos": "Verb",
    "base": "ablehnen",
    "target": "lehne / ab"
  },
  {
    "id": 36,
    "sentence": "Ich suche eine neue {{c1::Stelle}}.",
    "blank": "Ich suche eine neue _____.",
    "revealed": "Ich suche eine neue Stelle.",
    "ru": "Я ищу новую работу / должность.",
    "grammar": "die Stelle · die Stellen",
    "translation": "место, должность",
    "pos": "Substantiv",
    "base": "die Stelle",
    "target": "Stelle"
  },
  {
    "id": 37,
    "sentence": "Ein Pass ist {{c1::erforderlich}}.",
    "blank": "Ein Pass ist _____.",
    "revealed": "Ein Pass ist erforderlich.",
    "ru": "Необходим паспорт.",
    "grammar": "",
    "translation": "необходимый, требуемый",
    "pos": "Adjektiv",
    "base": "erforderlich",
    "target": "erforderlich"
  },
  {
    "id": 38,
    "sentence": "Ich {{c1::melde}} mich für den Kurs {{c1::an}}.",
    "blank": "Ich _____ mich für den Kurs _____.",
    "revealed": "Ich melde mich für den Kurs an.",
    "ru": "Я записываюсь на курс.",
    "grammar": "sich anmelden · meldete sich an · hat sich angemeldet",
    "translation": "регистрироваться, записываться",
    "pos": "Verb",
    "base": "sich anmelden",
    "target": "melde / an"
  },
  {
    "id": 39,
    "sentence": "Hier besteht keine {{c1::Gefahr}}.",
    "blank": "Hier besteht keine _____.",
    "revealed": "Hier besteht keine Gefahr.",
    "ru": "Здесь нет опасности.",
    "grammar": "die Gefahr · die Gefahren",
    "translation": "опасность",
    "pos": "Substantiv",
    "base": "die Gefahr",
    "target": "Gefahr"
  },
  {
    "id": 40,
    "sentence": "Meine Freundin ist sehr {{c1::zuverlässig}}.",
    "blank": "Meine Freundin ist sehr _____.",
    "revealed": "Meine Freundin ist sehr zuverlässig.",
    "ru": "Моя подруга очень надёжная.",
    "grammar": "",
    "translation": "надёжный",
    "pos": "Adjektiv",
    "base": "zuverlässig",
    "target": "zuverlässig"
  },
  {
    "id": 41,
    "sentence": "Ich kann dir diesen Kuchen {{c1::empfehlen}}.",
    "blank": "Ich kann dir diesen Kuchen _____.",
    "revealed": "Ich kann dir diesen Kuchen empfehlen.",
    "ru": "Я могу порекомендовать тебе этот пирог.",
    "grammar": "empfehlen · du empfiehlst / er empfiehlt · empfahl · hat empfohlen",
    "translation": "рекомендовать",
    "pos": "Verb",
    "base": "empfehlen",
    "target": "empfehlen"
  },
  {
    "id": 42,
    "sentence": "Ich habe viel {{c1::Erfahrung}} mit Kunden.",
    "blank": "Ich habe viel _____ mit Kunden.",
    "revealed": "Ich habe viel Erfahrung mit Kunden.",
    "ru": "У меня большой опыт работы с клиентами.",
    "grammar": "die Erfahrung · die Erfahrungen",
    "translation": "опыт",
    "pos": "Substantiv",
    "base": "die Erfahrung",
    "target": "Erfahrung"
  },
  {
    "id": 43,
    "sentence": "Das Kleid ist schön, {{c1::allerdings}} sehr teuer.",
    "blank": "Das Kleid ist schön, _____ sehr teuer.",
    "revealed": "Das Kleid ist schön, allerdings sehr teuer.",
    "ru": "Платье красивое, однако очень дорогое.",
    "grammar": "",
    "translation": "однако, правда",
    "pos": "Adverb",
    "base": "allerdings",
    "target": "allerdings"
  },
  {
    "id": 44,
    "sentence": "Das Wetter ist heute {{c1::angenehm}}.",
    "blank": "Das Wetter ist heute _____.",
    "revealed": "Das Wetter ist heute angenehm.",
    "ru": "Сегодня приятная погода.",
    "grammar": "",
    "translation": "приятный",
    "pos": "Adjektiv",
    "base": "angenehm",
    "target": "angenehm"
  },
  {
    "id": 45,
    "sentence": "Ich muss heute die Post {{c1::erledigen}}.",
    "blank": "Ich muss heute die Post _____.",
    "revealed": "Ich muss heute die Post erledigen.",
    "ru": "Мне нужно сегодня разобраться с почтой.",
    "grammar": "erledigen · erledigte · hat erledigt",
    "translation": "выполнять, улаживать",
    "pos": "Verb",
    "base": "erledigen",
    "target": "erledigen"
  },
  {
    "id": 46,
    "sentence": "Ich sehe keinen {{c1::Unterschied}}.",
    "blank": "Ich sehe keinen _____.",
    "revealed": "Ich sehe keinen Unterschied.",
    "ru": "Я не вижу разницы.",
    "grammar": "der Unterschied · die Unterschiede",
    "translation": "разница, различие",
    "pos": "Substantiv",
    "base": "der Unterschied",
    "target": "Unterschied"
  },
  {
    "id": 47,
    "sentence": "Ich bin krank, {{c1::deswegen}} bleibe ich zu Hause.",
    "blank": "Ich bin krank, _____ bleibe ich zu Hause.",
    "revealed": "Ich bin krank, deswegen bleibe ich zu Hause.",
    "ru": "Я болею, поэтому остаюсь дома.",
    "grammar": "",
    "translation": "поэтому",
    "pos": "Adverb",
    "base": "deswegen",
    "target": "deswegen"
  },
  {
    "id": 48,
    "sentence": "Ich {{c1::stelle}} einen Fehler {{c1::fest}}.",
    "blank": "Ich _____ einen Fehler _____.",
    "revealed": "Ich stelle einen Fehler fest.",
    "ru": "Я обнаруживаю ошибку.",
    "grammar": "feststellen · stellte fest · hat festgestellt",
    "translation": "устанавливать, констатировать; обнаруживать",
    "pos": "Verb",
    "base": "feststellen",
    "target": "stelle / fest"
  },
  {
    "id": 49,
    "sentence": "Bitte hör {{c1::aufmerksam}} zu.",
    "blank": "Bitte hör _____ zu.",
    "revealed": "Bitte hör aufmerksam zu.",
    "ru": "Пожалуйста, слушай внимательно.",
    "grammar": "",
    "translation": "внимательно; внимательный",
    "pos": "Adjektiv",
    "base": "aufmerksam",
    "target": "aufmerksam"
  },
  {
    "id": 50,
    "sentence": "Deutsch B1 ist eine wichtige {{c1::Voraussetzung}}.",
    "blank": "Deutsch B1 ist eine wichtige _____.",
    "revealed": "Deutsch B1 ist eine wichtige Voraussetzung.",
    "ru": "Немецкий B1 — важное требование / условие.",
    "grammar": "die Voraussetzung · die Voraussetzungen",
    "translation": "условие, предпосылка",
    "pos": "Substantiv",
    "base": "die Voraussetzung",
    "target": "Voraussetzung"
  },
  {
    "id": 51,
    "sentence": "Meine Freundin {{c1::unterstützt}} mich.",
    "blank": "Meine Freundin _____ mich.",
    "revealed": "Meine Freundin unterstützt mich.",
    "ru": "Моя подруга меня поддерживает.",
    "grammar": "unterstützen · unterstützte · hat unterstützt",
    "translation": "поддерживать",
    "pos": "Verb",
    "base": "unterstützen",
    "target": "unterstützt"
  },
  {
    "id": 52,
    "sentence": "Danke für deine {{c1::Unterstützung}}.",
    "blank": "Danke für deine _____.",
    "revealed": "Danke für deine Unterstützung.",
    "ru": "Спасибо за твою поддержку.",
    "grammar": "die Unterstützung · die Unterstützungen",
    "translation": "поддержка",
    "pos": "Substantiv",
    "base": "die Unterstützung",
    "target": "Unterstützung"
  },
  {
    "id": 53,
    "sentence": "Ich rufe dich an, {{c1::sobald}} ich zu Hause bin.",
    "blank": "Ich rufe dich an, _____ ich zu Hause bin.",
    "revealed": "Ich rufe dich an, sobald ich zu Hause bin.",
    "ru": "Я позвоню тебе, как только буду дома.",
    "grammar": "",
    "translation": "как только",
    "pos": "Konjunktion",
    "base": "sobald",
    "target": "sobald"
  },
  {
    "id": 54,
    "sentence": "Dieses Café ist sehr {{c1::beliebt}}.",
    "blank": "Dieses Café ist sehr _____.",
    "revealed": "Dieses Café ist sehr beliebt.",
    "ru": "Это кафе очень популярное.",
    "grammar": "",
    "translation": "популярный, любимый",
    "pos": "Adjektiv",
    "base": "beliebt",
    "target": "beliebt"
  },
  {
    "id": 55,
    "sentence": "Sie {{c1::bietet}} mir Kaffee {{c1::an}}.",
    "blank": "Sie _____ mir Kaffee _____.",
    "revealed": "Sie bietet mir Kaffee an.",
    "ru": "Она предлагает мне кофе.",
    "grammar": "anbieten · bot an · hat angeboten",
    "translation": "предлагать",
    "pos": "Verb",
    "base": "anbieten",
    "target": "bietet / an"
  },
  {
    "id": 56,
    "sentence": "Die {{c1::Veranstaltung}} beginnt um acht.",
    "blank": "Die _____ beginnt um acht.",
    "revealed": "Die Veranstaltung beginnt um acht.",
    "ru": "Мероприятие начинается в восемь.",
    "grammar": "die Veranstaltung · die Veranstaltungen",
    "translation": "мероприятие",
    "pos": "Substantiv",
    "base": "die Veranstaltung",
    "target": "Veranstaltung"
  },
  {
    "id": 57,
    "sentence": "{{c1::Solange}} es regnet, bleibe ich hier.",
    "blank": "_____ es regnet, bleibe ich hier.",
    "revealed": "Solange es regnet, bleibe ich hier.",
    "ru": "Пока идёт дождь, я останусь здесь.",
    "grammar": "",
    "translation": "пока, до тех пор пока",
    "pos": "Konjunktion",
    "base": "solange",
    "target": "Solange"
  },
  {
    "id": 58,
    "sentence": "Ich {{c1::bewerbe}} mich um eine Stelle.",
    "blank": "Ich _____ mich um eine Stelle.",
    "revealed": "Ich bewerbe mich um eine Stelle.",
    "ru": "Я подаю заявку на вакансию.",
    "grammar": "sich bewerben um + Akk. · du bewirbst dich / er bewirbt sich · bewarb sich · hat sich beworben",
    "translation": "подавать заявку на",
    "pos": "Verb",
    "base": "sich bewerben um + Akk.",
    "target": "bewerbe"
  },
  {
    "id": 59,
    "sentence": "Ich bin vom Film {{c1::enttäuscht}}.",
    "blank": "Ich bin vom Film _____.",
    "revealed": "Ich bin vom Film enttäuscht.",
    "ru": "Я разочарована фильмом.",
    "grammar": "",
    "translation": "разочарованный",
    "pos": "Adjektiv",
    "base": "enttäuscht",
    "target": "enttäuscht"
  },
  {
    "id": 60,
    "sentence": "Wir haben eine klare {{c1::Vereinbarung}}.",
    "blank": "Wir haben eine klare _____.",
    "revealed": "Wir haben eine klare Vereinbarung.",
    "ru": "У нас есть чёткая договорённость.",
    "grammar": "die Vereinbarung · die Vereinbarungen",
    "translation": "договорённость, соглашение",
    "pos": "Substantiv",
    "base": "die Vereinbarung",
    "target": "Vereinbarung"
  },
  {
    "id": 61,
    "sentence": "Hier ist Rauchen nicht {{c1::erlaubt}}.",
    "blank": "Hier ist Rauchen nicht _____.",
    "revealed": "Hier ist Rauchen nicht erlaubt.",
    "ru": "Здесь курить не разрешено.",
    "grammar": "erlauben · erlaubte · hat erlaubt",
    "translation": "разрешать",
    "pos": "Verb",
    "base": "erlauben",
    "target": "erlaubt"
  },
  {
    "id": 62,
    "sentence": "Ich schicke heute meine {{c1::Bewerbung}}.",
    "blank": "Ich schicke heute meine _____.",
    "revealed": "Ich schicke heute meine Bewerbung.",
    "ru": "Я сегодня отправляю свою заявку на работу.",
    "grammar": "die Bewerbung · die Bewerbungen",
    "translation": "заявка (особенно на работу); пакет документов",
    "pos": "Substantiv",
    "base": "die Bewerbung",
    "target": "Bewerbung"
  },
  {
    "id": 63,
    "sentence": "{{c1::Inzwischen}} wohne ich seit Jahren in München.",
    "blank": "_____ wohne ich seit Jahren in München.",
    "revealed": "Inzwischen wohne ich seit Jahren in München.",
    "ru": "К настоящему времени я уже много лет живу в Мюнхене.",
    "grammar": "",
    "translation": "тем временем, к настоящему времени",
    "pos": "Adverb",
    "base": "inzwischen",
    "target": "Inzwischen"
  },
  {
    "id": 64,
    "sentence": "Die Prüfung war {{c1::erfolgreich}}.",
    "blank": "Die Prüfung war _____.",
    "revealed": "Die Prüfung war erfolgreich.",
    "ru": "Экзамен прошёл успешно.",
    "grammar": "",
    "translation": "успешный",
    "pos": "Adjektiv",
    "base": "erfolgreich",
    "target": "erfolgreich"
  },
  {
    "id": 65,
    "sentence": "Ich {{c1::gewöhne}} mich an das Wetter.",
    "blank": "Ich _____ mich an das Wetter.",
    "revealed": "Ich gewöhne mich an das Wetter.",
    "ru": "Я привыкаю к погоде.",
    "grammar": "sich gewöhnen an + Akk. · gewöhnte sich · hat sich gewöhnt",
    "translation": "привыкать к",
    "pos": "Verb",
    "base": "sich gewöhnen an + Akk.",
    "target": "gewöhne"
  },
  {
    "id": 66,
    "sentence": "Sie macht eine {{c1::Ausbildung}} als Köchin.",
    "blank": "Sie macht eine _____ als Köchin.",
    "revealed": "Sie macht eine Ausbildung als Köchin.",
    "ru": "Она получает профессию повара.",
    "grammar": "die Ausbildung · die Ausbildungen",
    "translation": "профобучение, образование",
    "pos": "Substantiv",
    "base": "die Ausbildung",
    "target": "Ausbildung"
  },
  {
    "id": 67,
    "sentence": "{{c1::Schließlich}} haben wir eine Lösung gefunden.",
    "blank": "_____ haben wir eine Lösung gefunden.",
    "revealed": "Schließlich haben wir eine Lösung gefunden.",
    "ru": "В конце концов мы нашли решение.",
    "grammar": "",
    "translation": "в конце концов, наконец",
    "pos": "Adverb",
    "base": "schließlich",
    "target": "Schließlich"
  },
  {
    "id": 68,
    "sentence": "Ich möchte meinen Vertrag {{c1::kündigen}}.",
    "blank": "Ich möchte meinen Vertrag _____.",
    "revealed": "Ich möchte meinen Vertrag kündigen.",
    "ru": "Я хочу расторгнуть договор.",
    "grammar": "kündigen · kündigte · hat gekündigt",
    "translation": "увольняться; расторгать",
    "pos": "Verb",
    "base": "kündigen",
    "target": "kündigen"
  },
  {
    "id": 69,
    "sentence": "Fotografieren ist hier nicht {{c1::erlaubt}}.",
    "blank": "Fotografieren ist hier nicht _____.",
    "revealed": "Fotografieren ist hier nicht erlaubt.",
    "ru": "Фотографировать здесь не разрешено.",
    "grammar": "",
    "translation": "разрешённый, допустимый",
    "pos": "Adjektiv",
    "base": "erlaubt",
    "target": "erlaubt"
  },
  {
    "id": 70,
    "sentence": "Für die Stelle braucht man {{c1::Kenntnisse}} in Deutsch.",
    "blank": "Für die Stelle braucht man _____ in Deutsch.",
    "revealed": "Für die Stelle braucht man Kenntnisse in Deutsch.",
    "ru": "Для этой должности нужны знания немецкого.",
    "grammar": "die Kenntnis · die Kenntnisse (meist Plural in dieser Bedeutung)",
    "translation": "знания",
    "pos": "Substantiv",
    "base": "die Kenntnisse",
    "target": "Kenntnisse"
  },
  {
    "id": 71,
    "sentence": "Wir müssen das Problem {{c1::lösen}}.",
    "blank": "Wir müssen das Problem _____.",
    "revealed": "Wir müssen das Problem lösen.",
    "ru": "Нам нужно решить проблему.",
    "grammar": "lösen · löste · hat gelöst",
    "translation": "решать; освобождать",
    "pos": "Verb",
    "base": "lösen",
    "target": "lösen"
  },
  {
    "id": 72,
    "sentence": "Geduld ist eine wichtige {{c1::Fähigkeit}}.",
    "blank": "Geduld ist eine wichtige _____.",
    "revealed": "Geduld ist eine wichtige Fähigkeit.",
    "ru": "Терпение — важный навык.",
    "grammar": "die Fähigkeit · die Fähigkeiten",
    "translation": "способность, навык",
    "pos": "Substantiv",
    "base": "die Fähigkeit",
    "target": "Fähigkeit"
  },
  {
    "id": 73,
    "sentence": "Ich mag München {{c1::besonders}} im Sommer.",
    "blank": "Ich mag München _____ im Sommer.",
    "revealed": "Ich mag München besonders im Sommer.",
    "ru": "Мне особенно нравится Мюнхен летом.",
    "grammar": "",
    "translation": "особенно",
    "pos": "Adverb",
    "base": "besonders",
    "target": "besonders"
  },
  {
    "id": 74,
    "sentence": "Wir kochen heute {{c1::gemeinsam}}.",
    "blank": "Wir kochen heute _____.",
    "revealed": "Wir kochen heute gemeinsam.",
    "ru": "Сегодня мы готовим вместе.",
    "grammar": "",
    "translation": "совместный; вместе, совместно",
    "pos": "Adjektiv/Adverb",
    "base": "gemeinsam",
    "target": "gemeinsam"
  },
  {
    "id": 75,
    "sentence": "Das {{c1::überzeugt}} mich nicht.",
    "blank": "Das _____ mich nicht.",
    "revealed": "Das überzeugt mich nicht.",
    "ru": "Это меня не убеждает.",
    "grammar": "überzeugen · überzeugte · hat überzeugt",
    "translation": "убеждать",
    "pos": "Verb",
    "base": "überzeugen",
    "target": "überzeugt"
  },
  {
    "id": 76,
    "sentence": "Ich kenne die {{c1::Umgebung}} gut.",
    "blank": "Ich kenne die _____ gut.",
    "revealed": "Ich kenne die Umgebung gut.",
    "ru": "Я хорошо знаю окрестности.",
    "grammar": "die Umgebung · die Umgebungen",
    "translation": "окружение, окрестности",
    "pos": "Substantiv",
    "base": "die Umgebung",
    "target": "Umgebung"
  },
  {
    "id": 77,
    "sentence": "Ich warte {{c1::höchstens}} zehn Minuten.",
    "blank": "Ich warte _____ zehn Minuten.",
    "revealed": "Ich warte höchstens zehn Minuten.",
    "ru": "Я подожду максимум десять минут.",
    "grammar": "",
    "translation": "максимум, не более",
    "pos": "Adverb",
    "base": "höchstens",
    "target": "höchstens"
  },
  {
    "id": 78,
    "sentence": "Ich {{c1::stimme}} dir {{c1::zu}}.",
    "blank": "Ich _____ dir _____.",
    "revealed": "Ich stimme dir zu.",
    "ru": "Я с тобой согласна.",
    "grammar": "zustimmen · stimmte zu · hat zugestimmt",
    "translation": "соглашаться",
    "pos": "Verb",
    "base": "zustimmen",
    "target": "stimme / zu"
  },
  {
    "id": 79,
    "sentence": "Mein Fahrlehrer ist sehr {{c1::geduldig}}.",
    "blank": "Mein Fahrlehrer ist sehr _____.",
    "revealed": "Mein Fahrlehrer ist sehr geduldig.",
    "ru": "Мой инструктор по вождению очень терпеливый.",
    "grammar": "",
    "translation": "терпеливый",
    "pos": "Adjektiv",
    "base": "geduldig",
    "target": "geduldig"
  },
  {
    "id": 80,
    "sentence": "Sie haben eine gute {{c1::Beziehung}}.",
    "blank": "Sie haben eine gute _____.",
    "revealed": "Sie haben eine gute Beziehung.",
    "ru": "У них хорошие отношения.",
    "grammar": "die Beziehung · die Beziehungen",
    "translation": "отношения, связь",
    "pos": "Substantiv",
    "base": "die Beziehung",
    "target": "Beziehung"
  },
  {
    "id": 81,
    "sentence": "Das {{c1::hängt}} vom Wetter {{c1::ab}}.",
    "blank": "Das _____ vom Wetter _____.",
    "revealed": "Das hängt vom Wetter ab.",
    "ru": "Это зависит от погоды.",
    "grammar": "abhängen von + Dat. · hing ab · hat abgehangen",
    "translation": "зависеть от",
    "pos": "Verb",
    "base": "abhängen von + Dat.",
    "target": "hängt / ab"
  },
  {
    "id": 82,
    "sentence": "Sein {{c1::Verhalten}} war komisch.",
    "blank": "Sein _____ war komisch.",
    "revealed": "Sein Verhalten war komisch.",
    "ru": "Его поведение было странным.",
    "grammar": "das Verhalten · meist ohne Plural",
    "translation": "поведение",
    "pos": "Substantiv",
    "base": "das Verhalten",
    "target": "Verhalten"
  },
  {
    "id": 83,
    "sentence": "{{c1::Möglicherweise}} komme ich später.",
    "blank": "_____ komme ich später.",
    "revealed": "Möglicherweise komme ich später.",
    "ru": "Возможно, я приду позже.",
    "grammar": "",
    "translation": "возможно",
    "pos": "Adverb",
    "base": "möglicherweise",
    "target": "Möglicherweise"
  },
  {
    "id": 84,
    "sentence": "Ich bin das Wetter {{c1::gewohnt}}.",
    "blank": "Ich bin das Wetter _____.",
    "revealed": "Ich bin das Wetter gewohnt.",
    "ru": "Я привыкла к этой погоде.",
    "grammar": "",
    "translation": "привыкший к чему-либо; привычный",
    "pos": "Adjektiv",
    "base": "gewohnt",
    "target": "gewohnt"
  },
  {
    "id": 85,
    "sentence": "Der Fehler {{c1::fällt}} sofort {{c1::auf}}.",
    "blank": "Der Fehler _____ sofort _____.",
    "revealed": "Der Fehler fällt sofort auf.",
    "ru": "Ошибка сразу бросается в глаза.",
    "grammar": "auffallen · er fällt auf · fiel auf · ist aufgefallen",
    "translation": "бросаться в глаза, замечаться",
    "pos": "Verb",
    "base": "auffallen",
    "target": "fällt / auf"
  },
  {
    "id": 86,
    "sentence": "Kaffee am Morgen ist meine {{c1::Gewohnheit}}.",
    "blank": "Kaffee am Morgen ist meine _____.",
    "revealed": "Kaffee am Morgen ist meine Gewohnheit.",
    "ru": "Кофе утром — моя привычка.",
    "grammar": "die Gewohnheit · die Gewohnheiten",
    "translation": "привычка",
    "pos": "Substantiv",
    "base": "die Gewohnheit",
    "target": "Gewohnheit"
  },
  {
    "id": 87,
    "sentence": "{{c1::Jedenfalls}} möchte ich es versuchen.",
    "blank": "_____ möchte ich es versuchen.",
    "revealed": "Jedenfalls möchte ich es versuchen.",
    "ru": "Во всяком случае, я хочу попробовать.",
    "grammar": "",
    "translation": "во всяком случае",
    "pos": "Adverb",
    "base": "jedenfalls",
    "target": "Jedenfalls"
  },
  {
    "id": 88,
    "sentence": "Das Geld {{c1::reicht}} nicht {{c1::aus}}.",
    "blank": "Das Geld _____ nicht _____.",
    "revealed": "Das Geld reicht nicht aus.",
    "ru": "Денег недостаточно.",
    "grammar": "ausreichen · reichte aus · hat ausgereicht",
    "translation": "быть достаточным, хватать",
    "pos": "Verb",
    "base": "ausreichen",
    "target": "reicht / aus"
  },
  {
    "id": 89,
    "sentence": "Der Mitarbeiter war sehr {{c1::höflich}}.",
    "blank": "Der Mitarbeiter war sehr _____.",
    "revealed": "Der Mitarbeiter war sehr höflich.",
    "ru": "Сотрудник был очень вежлив.",
    "grammar": "",
    "translation": "вежливый",
    "pos": "Adjektiv",
    "base": "höflich",
    "target": "höflich"
  },
  {
    "id": 90,
    "sentence": "Homeoffice hat einen großen {{c1::Vorteil}}.",
    "blank": "Homeoffice hat einen großen _____.",
    "revealed": "Homeoffice hat einen großen Vorteil.",
    "ru": "У удалённой работы есть большое преимущество.",
    "grammar": "der Vorteil · die Vorteile",
    "translation": "преимущество",
    "pos": "Substantiv",
    "base": "der Vorteil",
    "target": "Vorteil"
  },
  {
    "id": 91,
    "sentence": "Ich möchte einen neuen Pass {{c1::beantragen}}.",
    "blank": "Ich möchte einen neuen Pass _____.",
    "revealed": "Ich möchte einen neuen Pass beantragen.",
    "ru": "Я хочу подать заявление на новый паспорт.",
    "grammar": "beantragen · beantragte · hat beantragt",
    "translation": "подавать заявление на",
    "pos": "Verb",
    "base": "beantragen",
    "target": "beantragen"
  },
  {
    "id": 92,
    "sentence": "Der Preis ist ein {{c1::Nachteil}}.",
    "blank": "Der Preis ist ein _____.",
    "revealed": "Der Preis ist ein Nachteil.",
    "ru": "Цена — это недостаток.",
    "grammar": "der Nachteil · die Nachteile",
    "translation": "недостаток",
    "pos": "Substantiv",
    "base": "der Nachteil",
    "target": "Nachteil"
  },
  {
    "id": 93,
    "sentence": "{{c1::Im Gegensatz dazu}} ist München sehr ruhig.",
    "blank": "_____ ist München sehr ruhig.",
    "revealed": "Im Gegensatz dazu ist München sehr ruhig.",
    "ru": "В отличие от этого Мюнхен очень спокойный.",
    "grammar": "",
    "translation": "в отличие от этого",
    "pos": "Verbindung",
    "base": "im Gegensatz dazu",
    "target": "Im Gegensatz dazu"
  },
  {
    "id": 94,
    "sentence": "Das war ein bisschen {{c1::peinlich}}.",
    "blank": "Das war ein bisschen _____.",
    "revealed": "Das war ein bisschen peinlich.",
    "ru": "Это было немного неловко.",
    "grammar": "",
    "translation": "неловкий, стыдный",
    "pos": "Adjektiv",
    "base": "peinlich",
    "target": "peinlich"
  },
  {
    "id": 95,
    "sentence": "Bitte {{c1::begründen}} Sie Ihre Meinung.",
    "blank": "Bitte _____ Sie Ihre Meinung.",
    "revealed": "Bitte begründen Sie Ihre Meinung.",
    "ru": "Пожалуйста, обоснуйте своё мнение.",
    "grammar": "begründen · begründete · hat begründet · очень полезно для экзамена",
    "translation": "обосновывать",
    "pos": "Verb",
    "base": "begründen",
    "target": "begründen"
  },
  {
    "id": 96,
    "sentence": "Ich schreibe eine {{c1::Beschwerde}}.",
    "blank": "Ich schreibe eine _____.",
    "revealed": "Ich schreibe eine Beschwerde.",
    "ru": "Я пишу жалобу.",
    "grammar": "die Beschwerde · die Beschwerden",
    "translation": "жалоба",
    "pos": "Substantiv",
    "base": "die Beschwerde",
    "target": "Beschwerde"
  },
  {
    "id": 97,
    "sentence": "{{c1::Einerseits}} ist es teuer, andererseits ist es bequem.",
    "blank": "_____ ist es teuer, andererseits ist es bequem.",
    "revealed": "Einerseits ist es teuer, andererseits ist es bequem.",
    "ru": "С одной стороны, это дорого, с другой — удобно.",
    "grammar": "",
    "translation": "с одной стороны … с другой стороны",
    "pos": "Verbindung",
    "base": "einerseits … andererseits",
    "target": "Einerseits"
  },
  {
    "id": 98,
    "sentence": "Sie {{c1::berichtet}} über ihre Reise.",
    "blank": "Sie _____ über ihre Reise.",
    "revealed": "Sie berichtet über ihre Reise.",
    "ru": "Она рассказывает о своей поездке.",
    "grammar": "berichten · berichtete · hat berichtet",
    "translation": "сообщать, рассказывать",
    "pos": "Verb",
    "base": "berichten",
    "target": "berichtet"
  },
  {
    "id": 99,
    "sentence": "Der Preis ist vom Datum {{c1::abhängig}}.",
    "blank": "Der Preis ist vom Datum _____.",
    "revealed": "Der Preis ist vom Datum abhängig.",
    "ru": "Цена зависит от даты.",
    "grammar": "",
    "translation": "зависимый от",
    "pos": "Adjektiv",
    "base": "abhängig",
    "target": "abhängig"
  },
  {
    "id": 100,
    "sentence": "Ich brauche eine {{c1::Erlaubnis}}.",
    "blank": "Ich brauche eine _____.",
    "revealed": "Ich brauche eine Erlaubnis.",
    "ru": "Мне нужно разрешение.",
    "grammar": "die Erlaubnis · die Erlaubnisse",
    "translation": "разрешение",
    "pos": "Substantiv",
    "base": "die Erlaubnis",
    "target": "Erlaubnis"
  },
  {
    "id": 101,
    "sentence": "Ich {{c1::beschäftige}} mich mit einem neuen Projekt.",
    "blank": "Ich _____ mich mit einem neuen Projekt.",
    "revealed": "Ich beschäftige mich mit einem neuen Projekt.",
    "ru": "Я занимаюсь новым проектом.",
    "grammar": "sich beschäftigen mit + Dat. · beschäftigte sich · hat sich beschäftigt",
    "translation": "заниматься чем-либо",
    "pos": "Verb",
    "base": "sich beschäftigen mit + Dat.",
    "target": "beschäftige"
  },
  {
    "id": 102,
    "sentence": "Die {{c1::Teilnahme}} ist kostenlos.",
    "blank": "Die _____ ist kostenlos.",
    "revealed": "Die Teilnahme ist kostenlos.",
    "ru": "Участие бесплатное.",
    "grammar": "die Teilnahme · die Teilnahmen",
    "translation": "участие",
    "pos": "Substantiv",
    "base": "die Teilnahme",
    "target": "Teilnahme"
  },
  {
    "id": 103,
    "sentence": "Ich mag {{c1::sowohl}} Kaffee als auch Tee.",
    "blank": "Ich mag _____ Kaffee als auch Tee.",
    "revealed": "Ich mag sowohl Kaffee als auch Tee.",
    "ru": "Я люблю и кофе, и чай.",
    "grammar": "",
    "translation": "как … так и",
    "pos": "Verbindung",
    "base": "sowohl … als auch",
    "target": "sowohl"
  },
  {
    "id": 104,
    "sentence": "Zwei Stunden sind {{c1::ausreichend}}.",
    "blank": "Zwei Stunden sind _____.",
    "revealed": "Zwei Stunden sind ausreichend.",
    "ru": "Двух часов достаточно.",
    "grammar": "",
    "translation": "достаточный",
    "pos": "Adjektiv",
    "base": "ausreichend",
    "target": "ausreichend"
  },
  {
    "id": 105,
    "sentence": "Ich {{c1::bemühe}} mich, pünktlich zu sein.",
    "blank": "Ich _____ mich, pünktlich zu sein.",
    "revealed": "Ich bemühe mich, pünktlich zu sein.",
    "ru": "Я стараюсь быть вовремя.",
    "grammar": "sich bemühen · bemühte sich · hat sich bemüht",
    "translation": "стараться, прилагать усилия",
    "pos": "Verb",
    "base": "sich bemühen",
    "target": "bemühe"
  },
  {
    "id": 106,
    "sentence": "Das ist eine wichtige {{c1::Anforderung}}.",
    "blank": "Das ist eine wichtige _____.",
    "revealed": "Das ist eine wichtige Anforderung.",
    "ru": "Это важное требование.",
    "grammar": "die Anforderung · die Anforderungen",
    "translation": "требование",
    "pos": "Substantiv",
    "base": "die Anforderung",
    "target": "Anforderung"
  },
  {
    "id": 107,
    "sentence": "Ich trinke {{c1::weder}} Cola noch Saft.",
    "blank": "Ich trinke _____ Cola noch Saft.",
    "revealed": "Ich trinke weder Cola noch Saft.",
    "ru": "Я не пью ни колу, ни сок.",
    "grammar": "",
    "translation": "ни … ни",
    "pos": "Verbindung",
    "base": "weder … noch",
    "target": "weder"
  },
  {
    "id": 108,
    "sentence": "Die Mitarbeiterin {{c1::berät}} mich.",
    "blank": "Die Mitarbeiterin _____ mich.",
    "revealed": "Die Mitarbeiterin berät mich.",
    "ru": "Сотрудница меня консультирует.",
    "grammar": "beraten · du berätst / er berät · beriet · hat beraten",
    "translation": "консультировать, советовать",
    "pos": "Verb",
    "base": "beraten",
    "target": "berät"
  },
  {
    "id": 109,
    "sentence": "Ich bin heute sehr {{c1::beschäftigt}}.",
    "blank": "Ich bin heute sehr _____.",
    "revealed": "Ich bin heute sehr beschäftigt.",
    "ru": "Я сегодня очень занята.",
    "grammar": "",
    "translation": "занятый",
    "pos": "Adjektiv",
    "base": "beschäftigt",
    "target": "beschäftigt"
  },
  {
    "id": 110,
    "sentence": "Ich akzeptiere diese {{c1::Bedingung}} nicht.",
    "blank": "Ich akzeptiere diese _____ nicht.",
    "revealed": "Ich akzeptiere diese Bedingung nicht.",
    "ru": "Я не принимаю это условие.",
    "grammar": "die Bedingung · die Bedingungen",
    "translation": "условие",
    "pos": "Substantiv",
    "base": "die Bedingung",
    "target": "Bedingung"
  },
  {
    "id": 111,
    "sentence": "Bitte {{c1::berücksichtigen}} Sie meine Situation.",
    "blank": "Bitte _____ Sie meine Situation.",
    "revealed": "Bitte berücksichtigen Sie meine Situation.",
    "ru": "Пожалуйста, учтите мою ситуацию.",
    "grammar": "berücksichtigen · berücksichtigte · hat berücksichtigt",
    "translation": "учитывать",
    "pos": "Verb",
    "base": "berücksichtigen",
    "target": "berücksichtigen"
  },
  {
    "id": 112,
    "sentence": "Der monatliche {{c1::Beitrag}} ist zu hoch.",
    "blank": "Der monatliche _____ ist zu hoch.",
    "revealed": "Der monatliche Beitrag ist zu hoch.",
    "ru": "Ежемесячный взнос слишком высокий.",
    "grammar": "der Beitrag · die Beiträge",
    "translation": "вклад; взнос; публикация",
    "pos": "Substantiv",
    "base": "der Beitrag",
    "target": "Beitrag"
  },
  {
    "id": 113,
    "sentence": "Bitte sprich {{c1::deutlich}}.",
    "blank": "Bitte sprich _____.",
    "revealed": "Bitte sprich deutlich.",
    "ru": "Пожалуйста, говори чётко.",
    "grammar": "",
    "translation": "ясный, отчётливый; чётко",
    "pos": "Adjektiv/Adverb",
    "base": "deutlich",
    "target": "deutlich"
  },
  {
    "id": 114,
    "sentence": "Wir {{c1::einigen}} uns auf Freitag.",
    "blank": "Wir _____ uns auf Freitag.",
    "revealed": "Wir einigen uns auf Freitag.",
    "ru": "Мы договариваемся на пятницу.",
    "grammar": "sich einigen · einigte sich · hat sich geeinigt",
    "translation": "договариваться, приходить к согласию",
    "pos": "Verb",
    "base": "sich einigen",
    "target": "einigen"
  },
  {
    "id": 115,
    "sentence": "Ich arbeite im kreativen {{c1::Bereich}}.",
    "blank": "Ich arbeite im kreativen _____.",
    "revealed": "Ich arbeite im kreativen Bereich.",
    "ru": "Я работаю в творческой сфере.",
    "grammar": "der Bereich · die Bereiche",
    "translation": "область, сфера",
    "pos": "Substantiv",
    "base": "der Bereich",
    "target": "Bereich"
  },
  {
    "id": 116,
    "sentence": "Ich {{c1::entdecke}} ein neues Café.",
    "blank": "Ich _____ ein neues Café.",
    "revealed": "Ich entdecke ein neues Café.",
    "ru": "Я открываю для себя новое кафе.",
    "grammar": "entdecken · entdeckte · hat entdeckt",
    "translation": "обнаруживать, открывать",
    "pos": "Verb",
    "base": "entdecken",
    "target": "entdecke"
  },
  {
    "id": 117,
    "sentence": "Ich brauche {{c1::dringend}} einen Kaffee.",
    "blank": "Ich brauche _____ einen Kaffee.",
    "revealed": "Ich brauche dringend einen Kaffee.",
    "ru": "Мне срочно нужен кофе.",
    "grammar": "",
    "translation": "срочный; срочно",
    "pos": "Adjektiv/Adverb",
    "base": "dringend",
    "target": "dringend"
  },
  {
    "id": 118,
    "sentence": "Ich warte noch auf den {{c1::Bescheid}}.",
    "blank": "Ich warte noch auf den _____.",
    "revealed": "Ich warte noch auf den Bescheid.",
    "ru": "Я всё ещё жду официального решения.",
    "grammar": "der Bescheid · die Bescheide",
    "translation": "официальное решение, уведомление",
    "pos": "Substantiv",
    "base": "der Bescheid",
    "target": "Bescheid"
  },
  {
    "id": 119,
    "sentence": "Der Film {{c1::enttäuscht}} mich.",
    "blank": "Der Film _____ mich.",
    "revealed": "Der Film enttäuscht mich.",
    "ru": "Фильм меня разочаровывает.",
    "grammar": "enttäuschen · enttäuschte · hat enttäuscht",
    "translation": "разочаровывать",
    "pos": "Verb",
    "base": "enttäuschen",
    "target": "enttäuscht"
  },
  {
    "id": 120,
    "sentence": "Ich suche eine neue {{c1::Beschäftigung}}.",
    "blank": "Ich suche eine neue _____.",
    "revealed": "Ich suche eine neue Beschäftigung.",
    "ru": "Я ищу новую работу / занятость.",
    "grammar": "die Beschäftigung · die Beschäftigungen",
    "translation": "занятость, занятие",
    "pos": "Substantiv",
    "base": "die Beschäftigung",
    "target": "Beschäftigung"
  },
  {
    "id": 121,
    "sentence": "Bitte sei {{c1::ehrlich}}.",
    "blank": "Bitte sei _____.",
    "revealed": "Bitte sei ehrlich.",
    "ru": "Пожалуйста, будь честной.",
    "grammar": "",
    "translation": "честный",
    "pos": "Adjektiv",
    "base": "ehrlich",
    "target": "ehrlich"
  },
  {
    "id": 122,
    "sentence": "Die Situation {{c1::entwickelt}} sich gut.",
    "blank": "Die Situation _____ sich gut.",
    "revealed": "Die Situation entwickelt sich gut.",
    "ru": "Ситуация развивается хорошо.",
    "grammar": "sich entwickeln · entwickelte sich · hat sich entwickelt",
    "translation": "развиваться",
    "pos": "Verb",
    "base": "sich entwickeln",
    "target": "entwickelt"
  },
  {
    "id": 123,
    "sentence": "Der {{c1::Betrieb}} hat zwanzig Mitarbeiter.",
    "blank": "Der _____ hat zwanzig Mitarbeiter.",
    "revealed": "Der Betrieb hat zwanzig Mitarbeiter.",
    "ru": "На предприятии двадцать сотрудников.",
    "grammar": "der Betrieb · die Betriebe",
    "translation": "предприятие, работа",
    "pos": "Substantiv",
    "base": "der Betrieb",
    "target": "Betrieb"
  },
  {
    "id": 124,
    "sentence": "Mir {{c1::fehlt}} die Zeit.",
    "blank": "Mir _____ die Zeit.",
    "revealed": "Mir fehlt die Zeit.",
    "ru": "Мне не хватает времени.",
    "grammar": "fehlen · fehlte · hat gefehlt",
    "translation": "отсутствовать; не хватать",
    "pos": "Verb",
    "base": "fehlen",
    "target": "fehlt"
  },
  {
    "id": 125,
    "sentence": "Ich möchte eine {{c1::eigen}}e Wohnung.",
    "blank": "Ich möchte eine _____e Wohnung.",
    "revealed": "Ich möchte eine eigene Wohnung.",
    "ru": "Я хочу собственную квартиру.",
    "grammar": "",
    "translation": "собственный",
    "pos": "Adjektiv",
    "base": "eigen",
    "target": "eigen"
  },
  {
    "id": 126,
    "sentence": "Das ist eine gute {{c1::Gelegenheit}}.",
    "blank": "Das ist eine gute _____.",
    "revealed": "Das ist eine gute Gelegenheit.",
    "ru": "Это хорошая возможность.",
    "grammar": "die Gelegenheit · die Gelegenheiten",
    "translation": "возможность, случай",
    "pos": "Substantiv",
    "base": "die Gelegenheit",
    "target": "Gelegenheit"
  },
  {
    "id": 127,
    "sentence": "Das Ticket {{c1::gilt}} nur heute.",
    "blank": "Das Ticket _____ nur heute.",
    "revealed": "Das Ticket gilt nur heute.",
    "ru": "Билет действует только сегодня.",
    "grammar": "gelten · du giltst / es gilt · galt · hat gegolten",
    "translation": "действовать; считаться",
    "pos": "Verb",
    "base": "gelten",
    "target": "gilt"
  },
  {
    "id": 128,
    "sentence": "Die {{c1::Gebühr}} beträgt zwanzig Euro.",
    "blank": "Die _____ beträgt zwanzig Euro.",
    "revealed": "Die Gebühr beträgt zwanzig Euro.",
    "ru": "Сбор составляет двадцать евро.",
    "grammar": "die Gebühr · die Gebühren",
    "translation": "сбор, плата",
    "pos": "Substantiv",
    "base": "die Gebühr",
    "target": "Gebühr"
  },
  {
    "id": 129,
    "sentence": "Allein zu Hause fühle ich mich manchmal {{c1::einsam}}.",
    "blank": "Allein zu Hause fühle ich mich manchmal _____.",
    "revealed": "Allein zu Hause fühle ich mich manchmal einsam.",
    "ru": "Одна дома я иногда чувствую себя одиноко.",
    "grammar": "",
    "translation": "одинокий",
    "pos": "Adjektiv",
    "base": "einsam",
    "target": "einsam"
  },
  {
    "id": 130,
    "sentence": "Ich {{c1::genieße}} meinen Kaffee.",
    "blank": "Ich _____ meinen Kaffee.",
    "revealed": "Ich genieße meinen Kaffee.",
    "ru": "Я наслаждаюсь своим кофе.",
    "grammar": "genießen · genoss · hat genossen",
    "translation": "наслаждаться",
    "pos": "Verb",
    "base": "genießen",
    "target": "genieße"
  },
  {
    "id": 131,
    "sentence": "Ich schicke die {{c1::Kündigung}} per Post.",
    "blank": "Ich schicke die _____ per Post.",
    "revealed": "Ich schicke die Kündigung per Post.",
    "ru": "Я отправляю расторжение договора по почте.",
    "grammar": "die Kündigung · die Kündigungen",
    "translation": "увольнение, расторжение",
    "pos": "Substantiv",
    "base": "die Kündigung",
    "target": "Kündigung"
  },
  {
    "id": 132,
    "sentence": "Ich {{c1::schaffe}} das heute nicht.",
    "blank": "Ich _____ das heute nicht.",
    "revealed": "Ich schaffe das heute nicht.",
    "ru": "Я сегодня с этим не справлюсь.",
    "grammar": "schaffen · schaffte · hat geschafft",
    "translation": "справляться, успевать",
    "pos": "Verb",
    "base": "schaffen",
    "target": "schaffe"
  },
  {
    "id": 133,
    "sentence": "Das Ergebnis ist {{c1::enttäuschend}}.",
    "blank": "Das Ergebnis ist _____.",
    "revealed": "Das Ergebnis ist enttäuschend.",
    "ru": "Результат разочаровывает.",
    "grammar": "",
    "translation": "разочаровывающий",
    "pos": "Adjektiv",
    "base": "enttäuschend",
    "target": "enttäuschend"
  },
  {
    "id": 134,
    "sentence": "Der {{c1::Schaden}} am Auto ist klein.",
    "blank": "Der _____ am Auto ist klein.",
    "revealed": "Der Schaden am Auto ist klein.",
    "ru": "Повреждение машины небольшое.",
    "grammar": "der Schaden · die Schäden",
    "translation": "ущерб, повреждение",
    "pos": "Substantiv",
    "base": "der Schaden",
    "target": "Schaden"
  },
  {
    "id": 135,
    "sentence": "Ich {{c1::gebe}} nicht {{c1::auf}}.",
    "blank": "Ich _____ nicht _____.",
    "revealed": "Ich gebe nicht auf.",
    "ru": "Я не сдаюсь.",
    "grammar": "aufgeben · du gibst auf / er gibt auf · gab auf · hat aufgegeben",
    "translation": "сдаваться; отказываться",
    "pos": "Verb",
    "base": "aufgeben",
    "target": "gebe / auf"
  },
  {
    "id": 136,
    "sentence": "Der {{c1::Umzug}} nach München war teuer.",
    "blank": "Der _____ nach München war teuer.",
    "revealed": "Der Umzug nach München war teuer.",
    "ru": "Переезд в Мюнхен был дорогим.",
    "grammar": "der Umzug · die Umzüge",
    "translation": "переезд",
    "pos": "Substantiv",
    "base": "der Umzug",
    "target": "Umzug"
  },
  {
    "id": 137,
    "sentence": "Das klingt {{c1::sinnvoll}}.",
    "blank": "Das klingt _____.",
    "revealed": "Das klingt sinnvoll.",
    "ru": "Это звучит разумно.",
    "grammar": "",
    "translation": "целесообразный, осмысленный",
    "pos": "Adjektiv",
    "base": "sinnvoll",
    "target": "sinnvoll"
  },
  {
    "id": 138,
    "sentence": "Ich {{c1::höre}} mit dem Rauchen {{c1::auf}}.",
    "blank": "Ich _____ mit dem Rauchen _____.",
    "revealed": "Ich höre mit dem Rauchen auf.",
    "ru": "Я прекращаю курить.",
    "grammar": "aufhören · hörte auf · hat aufgehört",
    "translation": "прекращать",
    "pos": "Verb",
    "base": "aufhören",
    "target": "höre / auf"
  },
  {
    "id": 139,
    "sentence": "Das war nicht meine {{c1::Absicht}}.",
    "blank": "Das war nicht meine _____.",
    "revealed": "Das war nicht meine Absicht.",
    "ru": "Это не было моим намерением.",
    "grammar": "die Absicht · die Absichten",
    "translation": "намерение",
    "pos": "Substantiv",
    "base": "die Absicht",
    "target": "Absicht"
  },
  {
    "id": 140,
    "sentence": "Ich {{c1::gebe}} zu viel Geld für Kaffee {{c1::aus}}.",
    "blank": "Ich _____ zu viel Geld für Kaffee _____.",
    "revealed": "Ich gebe zu viel Geld für Kaffee aus.",
    "ru": "Я трачу слишком много денег на кофе.",
    "grammar": "ausgeben · du gibst aus / er gibt aus · gab aus · hat ausgegeben",
    "translation": "тратить; выдавать",
    "pos": "Verb",
    "base": "ausgeben",
    "target": "gebe / aus"
  },
  {
    "id": 141,
    "sentence": "Wir haben {{c1::unterschiedlich}}e Meinungen.",
    "blank": "Wir haben _____e Meinungen.",
    "revealed": "Wir haben unterschiedliche Meinungen.",
    "ru": "У нас разные мнения.",
    "grammar": "",
    "translation": "различный, разный",
    "pos": "Adjektiv",
    "base": "unterschiedlich",
    "target": "unterschiedlich"
  },
  {
    "id": 142,
    "sentence": "Heute mache ich eine {{c1::Ausnahme}}.",
    "blank": "Heute mache ich eine _____.",
    "revealed": "Heute mache ich eine Ausnahme.",
    "ru": "Сегодня я сделаю исключение.",
    "grammar": "die Ausnahme · die Ausnahmen",
    "translation": "исключение",
    "pos": "Substantiv",
    "base": "die Ausnahme",
    "target": "Ausnahme"
  },
  {
    "id": 143,
    "sentence": "Bitte {{c1::beachten}} Sie die Öffnungszeiten.",
    "blank": "Bitte _____ Sie die Öffnungszeiten.",
    "revealed": "Bitte beachten Sie die Öffnungszeiten.",
    "ru": "Пожалуйста, обратите внимание на часы работы.",
    "grammar": "beachten · beachtete · hat beachtet",
    "translation": "учитывать, обращать внимание",
    "pos": "Verb",
    "base": "beachten",
    "target": "beachten"
  },
  {
    "id": 144,
    "sentence": "Mein erster {{c1::Eindruck}} war gut.",
    "blank": "Mein erster _____ war gut.",
    "revealed": "Mein erster Eindruck war gut.",
    "ru": "Моё первое впечатление было хорошим.",
    "grammar": "der Eindruck · die Eindrücke",
    "translation": "впечатление",
    "pos": "Substantiv",
    "base": "der Eindruck",
    "target": "Eindruck"
  },
  {
    "id": 145,
    "sentence": "Der Termin ist nicht mehr {{c1::verfügbar}}.",
    "blank": "Der Termin ist nicht mehr _____.",
    "revealed": "Der Termin ist nicht mehr verfügbar.",
    "ru": "Эта запись больше недоступна.",
    "grammar": "",
    "translation": "доступный, имеющийся",
    "pos": "Adjektiv",
    "base": "verfügbar",
    "target": "verfügbar"
  },
  {
    "id": 146,
    "sentence": "Gib mir bitte morgen {{c1::Bescheid}}.",
    "blank": "Gib mir bitte morgen _____.",
    "revealed": "Gib mir bitte morgen Bescheid.",
    "ru": "Дай мне, пожалуйста, знать завтра.",
    "grammar": "Bescheid geben · gab Bescheid · hat Bescheid gegeben",
    "translation": "дать знать, сообщить",
    "pos": "Verb",
    "base": "Bescheid geben",
    "target": "Bescheid"
  },
  {
    "id": 147,
    "sentence": "Stress hat großen {{c1::Einfluss}} auf mich.",
    "blank": "Stress hat großen _____ auf mich.",
    "revealed": "Stress hat großen Einfluss auf mich.",
    "ru": "Стресс сильно на меня влияет.",
    "grammar": "der Einfluss · die Einflüsse",
    "translation": "влияние",
    "pos": "Substantiv",
    "base": "der Einfluss",
    "target": "Einfluss"
  },
  {
    "id": 148,
    "sentence": "Die Firma {{c1::entlässt}} zehn Mitarbeiter.",
    "blank": "Die Firma _____ zehn Mitarbeiter.",
    "revealed": "Die Firma entlässt zehn Mitarbeiter.",
    "ru": "Компания увольняет десять сотрудников.",
    "grammar": "entlassen · du entlässt / er entlässt · entließ · hat entlassen",
    "translation": "увольнять; отпускать",
    "pos": "Verb",
    "base": "entlassen",
    "target": "entlässt"
  },
  {
    "id": 149,
    "sentence": "Das kann schlimme {{c1::Folge}}n haben.",
    "blank": "Das kann schlimme _____n haben.",
    "revealed": "Das kann schlimme Folgen haben.",
    "ru": "У этого могут быть плохие последствия.",
    "grammar": "die Folge · die Folgen",
    "translation": "последствие; серия",
    "pos": "Substantiv",
    "base": "die Folge",
    "target": "Folge"
  },
  {
    "id": 150,
    "sentence": "Ich habe das gestern {{c1::erfahren}}.",
    "blank": "Ich habe das gestern _____.",
    "revealed": "Ich habe das gestern erfahren.",
    "ru": "Я узнала об этом вчера.",
    "grammar": "erfahren · erfuhr · hat erfahren",
    "translation": "узнавать; испытывать",
    "pos": "Verb",
    "base": "erfahren",
    "target": "erfahren"
  },
  {
    "id": 151,
    "sentence": "Das {{c1::Gerät}} funktioniert nicht.",
    "blank": "Das _____ funktioniert nicht.",
    "revealed": "Das Gerät funktioniert nicht.",
    "ru": "Устройство не работает.",
    "grammar": "das Gerät · die Geräte",
    "translation": "прибор, устройство",
    "pos": "Substantiv",
    "base": "das Gerät",
    "target": "Gerät"
  },
  {
    "id": 152,
    "sentence": "Ich {{c1::erreiche}} den Zug noch.",
    "blank": "Ich _____ den Zug noch.",
    "revealed": "Ich erreiche den Zug noch.",
    "ru": "Я ещё успеваю на поезд.",
    "grammar": "erreichen · erreichte · hat erreicht",
    "translation": "достигать; дозваниваться",
    "pos": "Verb",
    "base": "erreichen",
    "target": "erreiche"
  },
  {
    "id": 153,
    "sentence": "Das {{c1::Gesetz}} gilt seit Januar.",
    "blank": "Das _____ gilt seit Januar.",
    "revealed": "Das Gesetz gilt seit Januar.",
    "ru": "Закон действует с января.",
    "grammar": "das Gesetz · die Gesetze",
    "translation": "закон",
    "pos": "Substantiv",
    "base": "das Gesetz",
    "target": "Gesetz"
  },
  {
    "id": 154,
    "sentence": "Ich {{c1::erkenne}} ihn sofort.",
    "blank": "Ich _____ ihn sofort.",
    "revealed": "Ich erkenne ihn sofort.",
    "ru": "Я сразу его узнаю.",
    "grammar": "erkennen · erkannte · hat erkannt",
    "translation": "узнавать, распознавать",
    "pos": "Verb",
    "base": "erkennen",
    "target": "erkenne"
  },
  {
    "id": 155,
    "sentence": "Ich hasse den {{c1::Haushalt}}.",
    "blank": "Ich hasse den _____.",
    "revealed": "Ich hasse den Haushalt.",
    "ru": "Я ненавижу домашние дела.",
    "grammar": "der Haushalt · die Haushalte",
    "translation": "домашнее хозяйство, бюджет",
    "pos": "Substantiv",
    "base": "der Haushalt",
    "target": "Haushalt"
  },
  {
    "id": 156,
    "sentence": "Sie {{c1::erwähnt}} das Problem nicht.",
    "blank": "Sie _____ das Problem nicht.",
    "revealed": "Sie erwähnt das Problem nicht.",
    "ru": "Она не упоминает проблему.",
    "grammar": "erwähnen · erwähnte · hat erwähnt",
    "translation": "упоминать",
    "pos": "Verb",
    "base": "erwähnen",
    "target": "erwähnt"
  },
  {
    "id": 157,
    "sentence": "Die {{c1::Herkunft}} spielt keine Rolle.",
    "blank": "Die _____ spielt keine Rolle.",
    "revealed": "Die Herkunft spielt keine Rolle.",
    "ru": "Происхождение не имеет значения.",
    "grammar": "die Herkunft · die Herkünfte",
    "translation": "происхождение",
    "pos": "Substantiv",
    "base": "die Herkunft",
    "target": "Herkunft"
  },
  {
    "id": 158,
    "sentence": "Bitte {{c1::teilen}} Sie mir Ihre Entscheidung {{c1::mit}}.",
    "blank": "Bitte _____ Sie mir Ihre Entscheidung _____.",
    "revealed": "Bitte teilen Sie mir Ihre Entscheidung mit.",
    "ru": "Пожалуйста, сообщите мне ваше решение.",
    "grammar": "mitteilen · teilte mit · hat mitgeteilt",
    "translation": "сообщать",
    "pos": "Verb",
    "base": "mitteilen",
    "target": "teilen / mit"
  },
  {
    "id": 159,
    "sentence": "Das war eine gute {{c1::Leistung}}.",
    "blank": "Das war eine gute _____.",
    "revealed": "Das war eine gute Leistung.",
    "ru": "Это был хороший результат / достижение.",
    "grammar": "die Leistung · die Leistungen",
    "translation": "результат, достижение; производительность",
    "pos": "Substantiv",
    "base": "die Leistung",
    "target": "Leistung"
  },
  {
    "id": 160,
    "sentence": "Ich {{c1::prüfe}} die Rechnung noch einmal.",
    "blank": "Ich _____ die Rechnung noch einmal.",
    "revealed": "Ich prüfe die Rechnung noch einmal.",
    "ru": "Я ещё раз проверяю счёт.",
    "grammar": "prüfen · prüfte · hat geprüft",
    "translation": "проверять, экзаменовать",
    "pos": "Verb",
    "base": "prüfen",
    "target": "prüfe"
  },
  {
    "id": 161,
    "sentence": "Es gibt einen {{c1::Mangel}} an Personal.",
    "blank": "Es gibt einen _____ an Personal.",
    "revealed": "Es gibt einen Mangel an Personal.",
    "ru": "Не хватает персонала.",
    "grammar": "der Mangel · die Mängel",
    "translation": "недостаток, нехватка",
    "pos": "Substantiv",
    "base": "der Mangel",
    "target": "Mangel"
  },
  {
    "id": 162,
    "sentence": "Ich {{c1::vergleiche}} die Preise.",
    "blank": "Ich _____ die Preise.",
    "revealed": "Ich vergleiche die Preise.",
    "ru": "Я сравниваю цены.",
    "grammar": "vergleichen · verglich · hat verglichen",
    "translation": "сравнивать",
    "pos": "Verb",
    "base": "vergleichen",
    "target": "vergleiche"
  },
  {
    "id": 163,
    "sentence": "Diese {{c1::Maßnahme}} soll helfen.",
    "blank": "Diese _____ soll helfen.",
    "revealed": "Diese Maßnahme soll helfen.",
    "ru": "Эта мера должна помочь.",
    "grammar": "die Maßnahme · die Maßnahmen",
    "translation": "мера, мероприятие",
    "pos": "Substantiv",
    "base": "die Maßnahme",
    "target": "Maßnahme"
  },
  {
    "id": 164,
    "sentence": "Ich {{c1::verspreche}}, pünktlich zu sein.",
    "blank": "Ich _____, pünktlich zu sein.",
    "revealed": "Ich verspreche, pünktlich zu sein.",
    "ru": "Я обещаю быть вовремя.",
    "grammar": "versprechen · du versprichst / er verspricht · versprach · hat versprochen",
    "translation": "обещать",
    "pos": "Verb",
    "base": "versprechen",
    "target": "verspreche"
  },
  {
    "id": 165,
    "sentence": "Bitte nimm {{c1::Rücksicht}} auf die Nachbarn.",
    "blank": "Bitte nimm _____ auf die Nachbarn.",
    "revealed": "Bitte nimm Rücksicht auf die Nachbarn.",
    "ru": "Пожалуйста, считайся с соседями.",
    "grammar": "die Rücksicht · die Rücksichten",
    "translation": "внимание, учёт интересов",
    "pos": "Substantiv",
    "base": "die Rücksicht",
    "target": "Rücksicht"
  },
  {
    "id": 166,
    "sentence": "Ich {{c1::ärgere}} mich über die Verspätung.",
    "blank": "Ich _____ mich über die Verspätung.",
    "revealed": "Ich ärgere mich über die Verspätung.",
    "ru": "Я злюсь из-за задержки.",
    "grammar": "sich ärgern über + Akk. · ärgerte sich · hat sich geärgert",
    "translation": "злиться, раздражаться из-за",
    "pos": "Verb",
    "base": "sich ärgern über + Akk.",
    "target": "ärgere"
  },
  {
    "id": 167,
    "sentence": "{{c1::Sicherheit}} ist mir wichtig.",
    "blank": "_____ ist mir wichtig.",
    "revealed": "Sicherheit ist mir wichtig.",
    "ru": "Безопасность для меня важна.",
    "grammar": "die Sicherheit · meist ohne Plural (Sicherheiten = гарантии/обеспечение)",
    "translation": "безопасность, уверенность",
    "pos": "Substantiv",
    "base": "die Sicherheit",
    "target": "Sicherheit"
  },
  {
    "id": 168,
    "sentence": "Ich {{c1::kenne}} mich hier nicht {{c1::aus}}.",
    "blank": "Ich _____ mich hier nicht _____.",
    "revealed": "Ich kenne mich hier nicht aus.",
    "ru": "Я здесь не ориентируюсь / не разбираюсь.",
    "grammar": "sich auskennen · kannte sich aus · hat sich ausgekannt",
    "translation": "разбираться, ориентироваться",
    "pos": "Verb",
    "base": "sich auskennen",
    "target": "kenne / aus"
  },
  {
    "id": 169,
    "sentence": "Meine {{c1::Tätigkeit}} ist kreativ.",
    "blank": "Meine _____ ist kreativ.",
    "revealed": "Meine Tätigkeit ist kreativ.",
    "ru": "Моя работа творческая.",
    "grammar": "die Tätigkeit · die Tätigkeiten",
    "translation": "деятельность, работа",
    "pos": "Substantiv",
    "base": "die Tätigkeit",
    "target": "Tätigkeit"
  },
  {
    "id": 170,
    "sentence": "Das Hotel {{c1::befindet}} sich im Zentrum.",
    "blank": "Das Hotel _____ sich im Zentrum.",
    "revealed": "Das Hotel befindet sich im Zentrum.",
    "ru": "Отель находится в центре.",
    "grammar": "sich befinden · befand sich · hat sich befunden",
    "translation": "находиться",
    "pos": "Verb",
    "base": "sich befinden",
    "target": "befindet"
  },
  {
    "id": 171,
    "sentence": "Wir suchen die {{c1::Ursache}}.",
    "blank": "Wir suchen die _____.",
    "revealed": "Wir suchen die Ursache.",
    "ru": "Мы ищем причину.",
    "grammar": "die Ursache · die Ursachen",
    "translation": "причина",
    "pos": "Substantiv",
    "base": "die Ursache",
    "target": "Ursache"
  },
  {
    "id": 172,
    "sentence": "Sport {{c1::trägt}} zur Gesundheit {{c1::bei}}.",
    "blank": "Sport _____ zur Gesundheit _____.",
    "revealed": "Sport trägt zur Gesundheit bei.",
    "ru": "Спорт способствует здоровью.",
    "grammar": "beitragen zu + Dat. · du trägst bei / er trägt bei · trug bei · hat beigetragen",
    "translation": "способствовать, вносить вклад в",
    "pos": "Verb",
    "base": "beitragen zu + Dat.",
    "target": "trägt / bei"
  },
  {
    "id": 173,
    "sentence": "Die {{c1::Verbindung}} nach Berlin ist direkt.",
    "blank": "Die _____ nach Berlin ist direkt.",
    "revealed": "Die Verbindung nach Berlin ist direkt.",
    "ru": "До Берлина есть прямое сообщение.",
    "grammar": "die Verbindung · die Verbindungen",
    "translation": "связь, соединение",
    "pos": "Substantiv",
    "base": "die Verbindung",
    "target": "Verbindung"
  },
  {
    "id": 174,
    "sentence": "Bitte {{c1::bestätigen}} Sie den Termin.",
    "blank": "Bitte _____ Sie den Termin.",
    "revealed": "Bitte bestätigen Sie den Termin.",
    "ru": "Пожалуйста, подтвердите встречу.",
    "grammar": "bestätigen · bestätigte · hat bestätigt",
    "translation": "подтверждать",
    "pos": "Verb",
    "base": "bestätigen",
    "target": "bestätigen"
  },
  {
    "id": 175,
    "sentence": "Was ist der {{c1::Zweck}} davon?",
    "blank": "Was ist der _____ davon?",
    "revealed": "Was ist der Zweck davon?",
    "ru": "Какова цель этого?",
    "grammar": "der Zweck · die Zwecke",
    "translation": "цель, назначение",
    "pos": "Substantiv",
    "base": "der Zweck",
    "target": "Zweck"
  },
  {
    "id": 176,
    "sentence": "Ich {{c1::beteilige}} mich an dem Projekt.",
    "blank": "Ich _____ mich an dem Projekt.",
    "revealed": "Ich beteilige mich an dem Projekt.",
    "ru": "Я участвую в проекте.",
    "grammar": "sich beteiligen an + Dat. · beteiligte sich · hat sich beteiligt",
    "translation": "участвовать в",
    "pos": "Verb",
    "base": "sich beteiligen an + Dat.",
    "target": "beteilige"
  },
  {
    "id": 177,
    "sentence": "Ich verstehe den {{c1::Zusammenhang}} nicht.",
    "blank": "Ich verstehe den _____ nicht.",
    "revealed": "Ich verstehe den Zusammenhang nicht.",
    "ru": "Я не понимаю взаимосвязь / контекст.",
    "grammar": "der Zusammenhang · die Zusammenhänge",
    "translation": "связь, взаимосвязь",
    "pos": "Substantiv",
    "base": "der Zusammenhang",
    "target": "Zusammenhang"
  },
  {
    "id": 178,
    "sentence": "Mir {{c1::fällt}} kein Wort {{c1::ein}}.",
    "blank": "Mir _____ kein Wort _____.",
    "revealed": "Mir fällt kein Wort ein.",
    "ru": "Мне не приходит в голову ни одного слова.",
    "grammar": "einfallen · mir fällt etwas ein · fiel ein · ist eingefallen",
    "translation": "приходить в голову",
    "pos": "Verb",
    "base": "einfallen",
    "target": "fällt / ein"
  },
  {
    "id": 179,
    "sentence": "Ich kann das Risiko nicht {{c1::einschätzen}}.",
    "blank": "Ich kann das Risiko nicht _____.",
    "revealed": "Ich kann das Risiko nicht einschätzen.",
    "ru": "Я не могу оценить риск.",
    "grammar": "einschätzen · schätzte ein · hat eingeschätzt",
    "translation": "оценивать",
    "pos": "Verb",
    "base": "einschätzen",
    "target": "einschätzen"
  },
  {
    "id": 180,
    "sentence": "Hier {{c1::entsteht}} ein neues Haus.",
    "blank": "Hier _____ ein neues Haus.",
    "revealed": "Hier entsteht ein neues Haus.",
    "ru": "Здесь строится / возникает новый дом.",
    "grammar": "entstehen · entstand · ist entstanden",
    "translation": "возникать, появляться",
    "pos": "Verb",
    "base": "entstehen",
    "target": "entsteht"
  },
  {
    "id": 181,
    "sentence": "Ich {{c1::denke}} über das Angebot {{c1::nach}}.",
    "blank": "Ich _____ über das Angebot _____.",
    "revealed": "Ich denke über das Angebot nach.",
    "ru": "Я обдумываю предложение.",
    "grammar": "nachdenken über + Akk. · dachte nach · hat nachgedacht",
    "translation": "размышлять о, обдумывать",
    "pos": "Verb",
    "base": "nachdenken über + Akk.",
    "target": "denke / nach"
  },
  {
    "id": 182,
    "sentence": "Die Prüfung {{c1::findet}} am Montag {{c1::statt}}.",
    "blank": "Die Prüfung _____ am Montag _____.",
    "revealed": "Die Prüfung findet am Montag statt.",
    "ru": "Экзамен состоится в понедельник.",
    "grammar": "stattfinden · fand statt · hat stattgefunden",
    "translation": "происходить, состояться",
    "pos": "Verb",
    "base": "stattfinden",
    "target": "findet / statt"
  },
  {
    "id": 183,
    "sentence": "Ich muss kurz {{c1::überlegen}}.",
    "blank": "Ich muss kurz _____.",
    "revealed": "Ich muss kurz überlegen.",
    "ru": "Мне нужно немного подумать.",
    "grammar": "überlegen · überlegte · hat überlegt",
    "translation": "обдумывать",
    "pos": "Verb",
    "base": "überlegen",
    "target": "überlegen"
  },
  {
    "id": 184,
    "sentence": "Ich {{c1::überweise}} die Miete morgen.",
    "blank": "Ich _____ die Miete morgen.",
    "revealed": "Ich überweise die Miete morgen.",
    "ru": "Я переведу арендную плату завтра.",
    "grammar": "überweisen · überwies · hat überwiesen",
    "translation": "переводить деньги",
    "pos": "Verb",
    "base": "überweisen",
    "target": "überweise"
  },
  {
    "id": 185,
    "sentence": "Was wollen wir am Wochenende {{c1::unternehmen}}?",
    "blank": "Was wollen wir am Wochenende _____?",
    "revealed": "Was wollen wir am Wochenende unternehmen?",
    "ru": "Что мы хотим поделать на выходных?",
    "grammar": "unternehmen · du unternimmst / er unternimmt · unternahm · hat unternommen",
    "translation": "предпринимать; делать",
    "pos": "Verb",
    "base": "unternehmen",
    "target": "unternehmen"
  },
  {
    "id": 186,
    "sentence": "Ich {{c1::verabrede}} mich mit einer Freundin.",
    "blank": "Ich _____ mich mit einer Freundin.",
    "revealed": "Ich verabrede mich mit einer Freundin.",
    "ru": "Я договариваюсь встретиться с подругой.",
    "grammar": "sich verabreden · verabredete sich · hat sich verabredet",
    "translation": "договариваться о встрече",
    "pos": "Verb",
    "base": "sich verabreden",
    "target": "verabrede"
  },
  {
    "id": 187,
    "sentence": "Ich muss die Blumen {{c1::gießen}}.",
    "blank": "Ich muss die Blumen _____.",
    "revealed": "Ich muss die Blumen gießen.",
    "ru": "Мне нужно полить цветы.",
    "grammar": "gießen · du gießt / er gießt · goss · hat gegossen",
    "translation": "поливать; лить",
    "pos": "Verb",
    "base": "gießen",
    "target": "gießen"
  }
];
